attic-labs/noms

- go/datas/database_common.go
- go/datas/http_batch_store_test.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- samples/go/demo-server/web_server_test.go
In the server side of the Remote Databse, the handler for
UpdateRoot now verifies that the new proposed Root is of a
legal type: empty map OR Map\<String, Ref\<Commit-like>>
Fixes #2116
> Validate type of new Root in root/ POST handler

- doc/intro.md
- go/chunks/memory_store.go
- go/types/batch_store.go
- go/walk/walk.go
The link to "HTTP protocol" in the intro doc is broken.
The other changes are updating out-of-date comments and error messages.
> fixing typos, stale comments, broken link

- doc/intro.md
Nitpick: "Amazon Dynamo" mention in the intro should be "Amazon DynamoDB".
[Amazon Dynamo](https://en.wikipedia.org/wiki/Dynamo_(storage_system)) is a particular system with which `DynamoStore` does not interact.
> Change "Amazon Dynamo" to "Amazon DynamoDB"

- cmd/noms/noms_ds.go
- cmd/noms/noms_ds_test.go
It (a) had a spurious blank line, (b) should print the dataset path not
just its ID, (c) should include the # for the hash. Now it says:
> noms ds -d path/to/db::my-dataset
Deleted path/to/db::my-dataset (was #lvnbmpj94r9h3nuaj1t0m4jeqp25o1ve)
>
> Tweak "Deleted dataset..." message

- js/src/browser/fetch.js
getAllResponseHeaders may contain empty rows
> JS: Partial fix for Safari

- samples/js/splore/src/main.js
If a struct does not have a name we used to have no label for the node.
It looks kind of funky so instead it will use the text "Struct" as the
label.
> Splore: Use Struct as label for non named structs

- cmd/noms/diff/diff.go
- go/types/path.go
- go/types/path_test.go
There are 3 ways to construct a Path: via methods like AddIndex, via
parsing/AddPath, and simply via using append() (since Path is a slice).
This patch deletes the former and leaves only (Maybe)ParsePath and
append() with the ability to manually create the various path parts.
> Simplify Path construction in Go

- cmd/noms/noms_sync.go
- cmd/noms/noms_sync_test.go
- go/datas/commit.go
- go/datas/database.go
- go/datas/database_common.go
- go/datas/local_database.go
- go/datas/pull.go
- go/datas/remote_database_client.go
- go/datas/remote_database_handlers.go
- go/dataset/dataset.go
- go/dataset/pull_test.go
The Dataset.Commit() code pathway still enforces fast-forward-only
behavior, but a new SetHead() method allows the HEAD of a Dataset to
be forced to any other Commit.
noms sync detects the case where the source Commit is not a descendent
of the provided sink Dataset's HEAD and uses the new API to force the
sink to the desired new Commit, printing out the now-abandoned old
HEAD.
Fixes #2240
> Allow Dataset HEAD to be set to non-fastforward commits

- js/package.json
- js/src/browser/bytes.js
- js/src/browser/fetch.js
- js/src/bytes-test.js
- js/src/bytes.js
- Lower case header names in fetch function
- fetchUint8Array should return an Uint8Array and not an ArrayBuffer
- Safari does not have slice on typed arrays
Fixes #2265
> JS: Safari 9 support

- samples/js/flickr/slurp/src/main.js
Based on the signature, this is how the copy should read.
> Fix type-o in Flickr sample

- go/datas/database.go
- go/datas/database_common.go
- go/datas/local_database.go
- go/datas/remote_database_client.go
In service of streaming set and map mutators, it'd be helpful for
ValueStore to implement some methods that are exposed only to other
code within the types package, even when a ValueStore is embedded
in a Database. That said, we don't want those methods to become a
part of the public Database API.
To enable this, this patch changes databaseCommon to embed a
*types.ValueStore, instead of composing one. This causes all the
ValueStore methods to be a part of the databaseCommon API, but
since all the Database construction methods return a Database by
interface, stuff like BatchStore() all gets masked. Thus, callers
still can't access ValueStore methods. Databases are passed into
the types package as ValueReadWriters, though, so code in there
can call any method on that interface -- including …
> Tweak interface/type embedding in databaseCommon

- js/package.json
- js/src/browser/bytes.js
- js/src/bytes-test.js
When we switched to big endian we forgot to update this.
Fixes #2338
> JS: Fix browser version of encodeUtf8

- samples/go/csv/csv-import/importer.go
- samples/go/csv/read.go
- samples/go/csv/schema.go
a piece of #2263 and a portion of #1610 - avoiding the performance issues of doing this on the actual import by instead making this option only do the detection and then writing the results to stdout (e.g. not performing the import)
> add csv-import --detect-column-types option

- go/types/compare_test.go
- go/types/map.go
- go/types/mapMutator.go
- go/types/map_test.go
- go/types/opcache.go
- go/types/opcache_compare.go
- go/types/opcache_test.go
- go/types/set.go
- go/types/setMutator.go
- go/types/set_test.go
- go/types/value_store.go
Streaming collections now share one ldb instance rather than having
1 ldb instance per collection.
> Add streaming set and improve streaming collection performance.

- cmd/noms/noms_sync.go
- cmd/noms/noms_sync_test.go
Starting with a very simple change to get my feet wet. 
This is a potential fix for #2053. Originally, syncing a commit to a non-existent dataset and an already sync'ed dataset resulted in the same message: "<src> is up to date"
This fix distinguishes 2 cases:
- Syncing to a new dataset prints "<dest> created"
- Syncing to an identical dataset prints "<dest> already up to date"
It also includes additional tests to sanity check the output. Please let me know if it'd be better to put the output tests in a separate test method. That was my first inclination, but I'm new to go and was afraid the repetition might go against the go grain.
> Fix noms_sync status message to indicate when new dataset is created

- js/package.json
- js/src/noms.js
- js/src/specs.js
- samples/js/splore/src/main.js
- samples/js/splore/src/node.js
Currently Splore can only open a database (db=) or a hash (hash=). This
removes the hash and replaces it with the much more general path (p=).
For example, what used to be:
?db=http://demo.noms.io&hash=abcd
is now:
?p=http://demo.noms.io::#abcd
and of course more complex paths work, like:
?p=http://demo.noms.io::#abcd.field[42].name
I've made 2 changes to the noms API for this:
1. Added support for an authorization token to DatabaseSpec.
2. Exposed getHashOfValue in noms.js.
> Let Splore open a noms path

- go/constants/http.go
- go/datas/database_server.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
Add a friendly message to the base path of the noms server, as opposed to an unfriendly and generic 404
> Add a friendly message to the base path of the noms server

- cmd/noms/diff/diff.go
- cmd/noms/diff/diff_test.go
- cmd/noms/noms_diff.go
- cmd/noms/noms_log.go
In 7c103344 I changed noms log to use left-right diff so that it
completes faster, but it changed noms diff to use left-right as well.
Noms diff is supposed to use best diff.
> Use best set/map diff in noms diff

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
- go/types/type.go
Basic support for creating Noms value from Go values as well as reading
Noms values onto Go values.
Typical usage:
```
// Go to Noms
type T struct {
S string
N int32
}
nomsVal, err := marshal.Marshal(T{"Hi", 42})
// Noms to Go
var goVal T
err = marshal.Unmarshal(types.NewStruct("T", types.StructData{
"S": types.String("Bye"),
"N": types.Number(555),
}, &goVal)
```
Fixes #1591
> Go marshal

- js/package.json
- js/src/struct-test.js
- js/src/struct.js
When we create JS struct classes we no longer creates properties for
`chunks`, `hash` or `type` (nor for `toString`, `hashOwnProperty` etc)
If you are using structs with field names that clashes with these then
use a `StructMirror`.
Fixes #2332
> JS: Do not shadow struct properties

- cmd/noms/diff/diff.go
This isn't triggering any problem in particular, I just noticed it. All
it meant was that noms log might take unnecessarily long with list diff
when there are a lot of changes.
> Add missing ==nil check to list diff

- samples/go/csv/csv-analyze/.gitignore
- samples/go/csv/csv-analyze/analyze.go
- samples/go/csv/csv-analyze/analyze_test.go
- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv_reader.go
- samples/go/csv/schema.go
- samples/go/csv/schema_test.go
Work in progress, but feedback welcome any time.
- create csv-analyze
- add initial version of detection of PKs
- move detect-columns from csv-import to csv-analyze
Working toward #1956, #2263, related to #1610.
> csv-analyze to detect column types and primary keys

- go/merge/three_way.go
- go/merge/three_way_test.go
Add the Go 'merge' package, which exports one function called ThreeWay().
ThreeWay() attempts a three-way merge between two candidates and a common
ancestor. It considers the three of them recursively, applying some simple rules:
- If any of the three nodes are different types: conflict
- If we are dealing with a map:
- If the same key is both removed and inserted wrt parent: conflict
- If the same key is inserted wrt parent, but with different values: conflict
- If we are dealing with a struct:
- same as map
- If we are dealing with a list:
- Same as map but substitute "index" for "key"
- If we are dealing with a set:
- If the same object is both removed and inserted wrt parent: conflict
... otherwise, the concurrent modification is allowed.
Currently, ThreeWay() only works on types.Map. …
> Go: Implement best-effort three-way merge for Maps

- go/perf/suite/suite.go
- go/perf/suite/suite_test.go
- samples/go/csv/csv-import/perf_test.go
Needed by Jenkins shared workspaces.
> Make perf suite testdata path configurable by -perf.testdata flag

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
When unmarshalling onto `interface{}` the following rules are used:
- `types.Bool` -> `bool`
- `types.List` -> `[]interface{}`
- `types.Map` -> `map[interface{}]interface{}`
- `types.Number` -> `float64`
- `types.String` -> `string`
Towards #2376
> Marshal and Unmarshal handling of interface{}

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
Make the name of the Noms struct start with a capital letter.
When unmarshalling a struct we now ignore the case.
Towards #2376
> Go Marshal: Title case struct names

- go/perf/suite/suite.go
- go/perf/suite/suite_test.go
This prepends a prefix to every dataset ID written by perf tests.
It will be used for namespacing the test results for different PRs.
Currently they're written to different databases, which isn't as good.
> Support a -perf.prefix flag for perf tests

- go/merge/three_way.go
- go/merge/three_way_ordered_sequence.go
- go/merge/three_way_test.go
merge.ThreeWay() is now willing to merge Structs as well as Maps, as long
as the Structs are all named the name thing. Other rules are the same
as for Map.
Toward #148
> Go: Add three-way merge for types.Struct

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
- samples/go/csv/read.go
- samples/go/csv/read_test.go
- samples/go/csv/write.go
- samples/go/csv/write_test.go
This is forked from the other PR that has importing to nested-maps.  I needed to have nested-maps in csv-import and/or read.go to properly test csv-export and/or write.go. I can merge the 2 PRs if that makes it easier to land.  This PR actually is the superset, so maybe I should just kill/close the other one?  Let me know how best to enable review/landing.  I am fine with waiting on this one until after the other one lands too.  Whatever works best for you.
> csv-import/csv-export support for compound keys/nested maps

- go/merge/three_way.go
- go/merge/three_way_keyval_test.go
- go/merge/three_way_set_test.go
- go/merge/three_way_test.go
merge.ThreeWay(SetA, SetB, Parent) essentially returns the union of
the three Sets.
Toward #148
> Add Set support to merge.ThreeWay

- go/merge/three_way.go
- go/merge/three_way_list.go
- go/merge/three_way_list_test.go
- go/merge/three_way_test.go
While the code in threeWayListMerge() starts similarly to that
in threeWayOrderedSequenceMerge(), the types of the channels
are different and trying to shoehorn them together would
remove a lot of clarity just for the sake of sharing maybe
15 lines of code.
Toward #148
> Add types.List support merge.ThreeWay()

- go/merge/three_way.go
Initially, this code used DiffLeftRight() for some kinds
of collections. Standardize on Diff().
Towards #148
> In merge.ThreeWay(), use Diff() across the board

- go/types/struct.go
- go/types/type.go
- samples/go/csv/read.go
- samples/go/csv/read_test.go
…n logic, and changes csv importing to strip csv name fields of invalid struct characters and changes spaces in field names to camel case. i.e. camel case is translated to camelCase.
Additional comments and conversation here. I was struggling to undo my fat finger rebase orz.
https://github.com/attic-labs/noms/pull/2437
> Add special encoding to csv imported struct fields

- samples/js/splore/build.py
The path to the noms sdk in the build script was not updated when the
js sdk was moved.
> Fix path in splore build script

- samples/go/noms-merge/.gitignore
- samples/go/noms-merge/main.go
- samples/go/noms-merge/main_test.go
This is a first pass at exposing the new merge package to users.  The
tool is very basic, and currently only works on datasets in the same
database. It requires the 'parent' (i.e. a common ancestor of the two
datasets being merged) to be provided by a commandline option; a
follow-on patch will make the code discover this ancestor automatically.
Toward #2445
> Introduce noms-merge, a standalone noms tool for merging datasets

- js/noms/.gitignore
- js/noms/package.json
- tools/build-js-documentation.py
Turns out that documentationjs reads the babelrc file from js/noms
which leads to us having to do npm install in js/noms. Therefore
putting the dev deps in there and running the script from there
makes things cleaner.
It also allows doing:
npm run build-docs
Towards #1471
> Drive js docs from npm script

- tools/build-js-documentation.py
There was a typo (missing comma) in the command.
> Build js docs correctly

- samples/go/poke/main.go
Before this, poke would drop any commit metadata from the dataset being modified. Now, it just pulls it forward.
> Make poke hang on to parent's Commit metadata

- go/datas/commit_test.go
- go/types/assert_type.go
- go/types/assert_type_test.go
For compound types (List, Set, Map, Ref) the concrete type may be a
union. If that is the case all the types in the union must be a
subtype of the concrete type's element type.
`C<T | V>` is a subtype of `C<S>` iff T is a subtype of S and V is a
subtype of S.
> Fix subtype issue with unions as elem types

- go/perf/suite/suite_test.go
This needs to be disabled so that test cases succeed when
building demo-server. Currently this fails because we build
with CodePipeline so the source code is not in a git repo
when getting built.
> Disable perf suite check for nomsRevision

- cmd/noms/noms_log.go
- go/datas/database_common.go
- go/marshal/decode_test.go
- go/spec/dataspec.go
- go/types/edit_distance.go
- go/types/meta_sequence.go
- go/types/string.go
- go/types/struct.go
- go/util/orderedparallel/ordered_parallel.go
- samples/go/blob-get/blob_get_test.go
- samples/go/csv/schema.go
- samples/go/hr/main.go
- samples/go/nomdex/parser.go
- samples/go/nomdex/query_range.go
- samples/go/noms-merge/main.go
Fixes are based on Go report card output:
- `gofmt -s` eliminates some duplication in struct/slice initialization
- `golint` found some issues like: `warning: should drop = nil from declaration of var XXX; it is the zero value`
- `golint` found some issues like: `warning: receiver name XXX should be consistent with previous receiver name YYY for ZZZ`
- `golint` says not to use underscores for function/variable names
- `golint` found several issues like: `warning: if block ends with a return statement, so drop this else and outdent its block`
No functional changes are included - just source code quality improvements.
> Improve code based on tool analysis feeback

- go/merge/three_way_list.go
- go/types/list.go
- go/types/list_iterator.go
- go/types/list_iterator_test.go
- go/types/opcache.go
- go/types/set_iterator_test.go
- go/types/util_test.go
When merge.ThreeWay() merges list splices, it frequently needs to
extract a slice of a List or check whether a given range of values is
exactly equal in two different Lists. Repeatedly Getting elements from
a List is expensive, because it creates a new cursor internally every
time. Adding IteratorAt(idx uint64) allows code to iterate over a
range of a List while only creating a cursor once. This allows a slice
of Values to be extracted or used in comparisons efficiently.
Toward #2445
> Go: Add List.IteratorAt() and use in list merging

- cmd/noms/noms_log.go
Quick little noms-log patch that fixes the help message for noms-log to turn off correctly
> Fix cmdline help message color argument

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
Small fix that changes the logic from using the delimiter specified delimiter to parse header arguments.
https://github.com/attic-labs/noms/issues/2456
> Fixes bug where delimiter applied to header arguments

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
Adds checks to ensure column types correspond to the number of header types, makes partial specification invalid and ensures header values are unique.
> Adds checks for bad column-type and header csv-import flag values

- go/merge/candidate.go
- go/merge/three_way.go
- go/merge/three_way_keyval_test.go
- go/merge/three_way_ordered_sequence.go
- go/merge/three_way_test.go
- samples/go/noms-merge/main.go
- samples/go/noms-merge/main_test.go
This patch modifies merge.ThreeWay() to take a callback that allows
for custom conflict resolution. The noms-merge command-line tool uses
this to inject a callback that accepts input from the console
dictating whether to accept the value from the 'left' or 'right' merge
candidates.
Toward #2445
> Update merge.ThreeWay() to allow very basic custom conflict resolution

- tools/noms/staging.py
Previously, it was required to already exist
> Allow stage.py to create the staging dir

- samples/js/flickr/slurp/src/main.js
Reject the promise when we get a fail status.
> flickr/slurp: Treat fail as an error

- go/datas/database_common.go
This comment was meant to be part of a previous patch. It points
out the code to which bug #2565 applies.
> Add comment referencing potential infinite Commit loop

- go/datas/commit.go
- go/datas/commit_test.go
- go/datas/pull.go
- go/types/ref_heap.go
- go/types/ref_heap_test.go
Once we integrate noms-merge into the `noms commit` command, this
function will allow us to stop requiring users to pass in the common
ancestor to be used when merging. The code can just find it and merge
away.
Toward #2535
> Add FindCommonAncestor for Commits

- js/noms/package.json
- js/noms/src/encoding-test.js
- js/noms/src/struct.js
- js/noms/src/type.js
This method was not being used.
Major Version Change: equals was part of exposed public API of *Desc
> Remove TypeDesc equals

- go/spec/commit_meta_test.go
The codecov results pointed out to me last week that I had never written specific tests for this. Adding now. It is being tested through noms_commit too, but this is better and more thorough.
> Add unit tests for commit metadata

- js/noms/package.json
- js/noms/src/absolute-path-test.js
- js/noms/src/absolute-path.js
- js/noms/src/database-test.js
- js/noms/src/database.js
- js/noms/src/dataset-test.js
- js/noms/src/dataset.js
- js/noms/src/specs-test.js
- js/noms/src/specs.js
- js/perf/codec-perf-rig/src/main.js
- js/perf/viewer/src/main.js
- samples/js/aggregate/src/main.js
- samples/js/counter/src/main.js
- samples/js/fb/find-photos/src/main.js
- samples/js/fb/slurp/src/main.js
- samples/js/flickr/find-photos/src/main.js
- samples/js/flickr/slurp/src/main.js
- samples/js/fs/src/main.js
- samples/js/url_fetch/src/main.js
Noms SDK users frequently shoot themselves in the foot because they're
holding onto an "old" Database object. That is, they have a Database
tucked away in some internal state, they call Commit() on it, and
don't replace the object in their internal state with the new Database
returned from Commit.
This PR fixes #2589 by changing the Database and Dataset JS API to be
in line with the proposal there.
> JS: Make Database a mutable API that vends immutable Datasets

- js/noms/src/json-convert-test.js
- js/noms/src/json-convert.js
Null values in struct field are handled by not skipping that field in
the noms type. Null values as elements in array cause an exception.
> Make jsonToNoms handle some null values

- go/perf/suite/suite.go
- go/perf/suite/suite_test.go
- samples/go/url-fetch/perf/perf_test.go
The subsequent runs of url-fetch on jenkins are way faster, and this
appears to be because commiting is much faster on subsequent runs. The
perf tests now use a new database each time.
> Run url-fetch perf tests against a fresh database each time

- tools/run-all-js-tests.py
When the flag is present we force update @attic/noms. This is useful
since a lot of the samples use file: dependencies which lack a version
so they do not get updated as normal dependencies do.
> Add --force to run-all-js-tests.py

- js/noms/src/database-test.js
- js/noms/src/database.js
- js/noms/src/dataset-test.js
- js/noms/src/remote-batch-store-fake.js
- js/noms/src/remote-batch-store-test.js
- js/noms/src/remote-batch-store.js
This patch brings JS into line with Go's handling of concurrent
commits to separate Datasets.
Fixes issue #2524
> JS: Auto-merge concurrent commits to noms datasets

- go/datas/database.go
- go/datas/database_test.go
- js/noms/package.json
- js/noms/src/database-test.js
- js/noms/src/database.js
This allows setting the meta field when you commit.
This is a version change because the signature of Database commit
changed in a non backwards compatible way. It now takes an optional
third options object instead of an optional array.
> JS: Add CommitOptions to commit method

- go/types/struct.go
- go/types/struct_test.go
- js/noms/package.json
- js/noms/src/struct-test.js
- js/noms/src/struct.js
This allows setting a field in a struct to a new type or to set a
non-existig field in a struct.
In JS this is done through the StructMirror.p.set and in Go this is
done through Struct Set.
Fixes #2181
> Allow struct set to cause a type change

- go/types/validating_batching_sink_test.go
The test now actually validates that processing the provided
hints populates the VBS' chunk cache
> Enhance TestValidatingBatchingSinkPrepare

- js/noms/src/fetch.js
- js/noms/src/http-batch-store-test.js
- js/noms/src/http-batch-store.js
The code in fetch.js and http_batch_store.js weren't really
agreeing on how HTTP failures were reported up the stack. Now,
they agree, and this allows HttpBatchStore.updateRoot() to
correctly detect a conflict response and return false.
This means that the merge logic in Database.commit() works right,
now.
Fixes #2699
> Correctly handle HTTP conflict status on updateRoot

- go/datas/database_common.go
- go/datas/database_test.go
- js/noms/src/database-test.js
- js/noms/src/database.js
Now that we're going to put in real commit-merge logic, we
can take out the very-old hack that deduplicated identical
commits.
Fixes #2720
> Remove commit de-duping

- js/eslintrc/package.json
This is so that we can have the clients depend on the fix.
> Update version of eslintrc

- go/marshal/decode.go
- go/marshal/decode_test.go
I need to unmarshal Noms Structs into arbitrarily-named Golang structs. Since this is already planned (https://github.com/attic-labs/noms/issues/2376), I went ahead and removed the code pointed by @aboodman and added a test case for that scenario.
> go/marshal: allow any struct names while unmarshaling.

- go/datas/commit.go
- go/datas/commit_options.go
- go/datas/commit_test.go
- go/datas/database_common.go
- go/datas/database_test.go
- go/datas/local_database.go
- go/datas/remote_database_client.go
- go/merge/three_way.go
- go/merge/three_way_keyval_test.go
This patch adds an optional MergePolicy field to CommitOptions. It's a
callback. If the caller sets it, then the commit code will look for a
common ancestor between the Dataset HEAD and the provided Commit. If
the caller-provided Commit descends from HEAD, then Commit proceeds as
normal.
If it does not, but there is a common ancestor, the code runs
merge.ThreeWay() on the values of the provided Commit, HEAD, and the
common ancestor, invoking the MergePolicy callback to resolve
conflicts. If merge succeeds, a merge Commit is created that descends
from both HEAD and the caller-provided Commit. This becomes the new
HEAD of the Dataset.
Towards #2534
> Go: add heuristic merge option to db.Commit()

- js/noms/package.json
- js/noms/src/specs-test.js
- js/noms/src/specs.js
The current implementation of pin means that programs like find-photos can't take a pinned path as it's <in-path> argument. This should re-enable that functionality.
Do I need to bump up the noms version for this change?
> Make pin return unchanged spec if it's already pinned

- js/babel-preset-noms/index.js
- js/babel-preset-noms/package.json
It wasn't working on the code coverage tests. Now I restored this
to what it was before these changes (minus removing some features
that chrome and node now supports out of the box)
> Fix babel-preset-noms

- go/marshal/decode.go
- go/marshal/encode.go
- go/marshal/encode_test.go
If you provide an omitempty tag and the Go value is the zero/empty value
then we do not include that field in the resulting Noms struct.
Towards #2376
> Add omitempty to Go marshal

- tools/publish-to-npm.py
I'm doing this in two steps to allow the builders to continue to work.
> Rename publish-js-sdk to publish-to-npm

- go/diff/diff.go
- go/diff/diff_test.go
- go/types/path.go
- go/types/path_test.go
I need this method in a couple of new places. It seems like it belongs in path.go.
> Add CopyAppend() method to types.Path

- go/util/receipts/receipts.go
- go/util/receipts/receipts_test.go
- samples/go/demo-server/main.go
- samples/go/demo-server/web_server.go
- samples/go/demo-server/web_server_test.go
- tools/crypto/receiptkey/main.go
- tools/crypto/receipttool/main.go
Private databases begin with "/p/" - for example, "/kalman" is not
private, but "/p/kalman" is private. They are not the same database.
The bulk of this work is the receipt infrastructure.
A receipt is form data that gives access to a database, encrypted using
secretbox. For example, "Database=/p/kalman&Date=12345678" might encrypt
to "SFH5bcIJ3_XgEbtmi_AdCKTItW20fl90czVl5_pF5PAXhNQ366U1yOpYGAjT".
- A new tool receiptkey generates random receipt (secretbox) keys.
- A new tool receipttool generates receipts for databases.
- demo-server has been updated to check for a receipt in the
Authorization header to access private databases.
receipttool and demo-server must be given the same receipt key.
> Implement private databases for the demo server

- js/noms/package.json
- js/noms/src/http-batch-store.js
- js/noms/src/noms.js
- js/noms/src/spec-test.js
- js/noms/src/spec.js
- samples/go/demo-server/web_server.go
- samples/js/photos/src/main.js
- samples/js/photos/src/params.js
The big change here is adding a new Spec class in spec.js. This replaces
DatabaseSpec/DatasetSpec/PathSpec in specs.js, but I'm leaving those in
and moving code over in a later patch. For now, only photos UI.
The photos UI change is to plumb through the authorization token through
the Spec code. For now, it's reading it from a URL parameter, but soon
I'll make it session based (probably localStorage).
The demo-server change is to add the Authorization header into CORS.
> Noms, demo-server, and photos UI changes to support auth

- go/datas/http_batch_store_test.go
The httpBatchStore test TestVersionMismatch() expects a panic,
but the test was actually potentially causing MULTIPLE panics.
One due to the version mismatch, and another due to using an
invalid root.
> Don't use invalid Root in bad version test

- go/types/value_store.go
- go/types/value_store_test.go
- go/util/sizecache/size_cache.go
- go/util/sizecache/size_cache_test.go
- js/noms/src/value-store-test.js
- js/noms/src/value-store.js
ValueStore caches Values that are read out of it, but it doesn't
do the same for Values that are written. This is because we expect
that reading Values shortly after writing them is an uncommon usage
pattern, and because the Chunks that make up novel Values are
generally efficiently retrievable from the BatchStore that backs
a ValueStore. The problem discovered in issue #2802 is that ValueStore
caches non-existence as well as existence of read Values. So, reading
a Value that doesn't exist in the DB would result in the ValueStore
permanently returning nil for that Value -- even if you then go and
write it to the DB.
This patch drops the cache entry for a Value whenever it's written.
Fixes #2802
> Clobber ValueStore cache entry on WriteValue

- go/datas/database_test.go
- go/datas/local_batch_store.go
- go/datas/local_database.go
There were several tests in the Database suites that were failing to
close test Databases that had orderedChunkCaches in them (backed by
levelDBs). Close them.
I was ALSO failing to destroy the cache used in LocalDatabase
instances only while testing Pull(). That's cleared up now as well.
> Close and destroy databases being left open during tests

- go/config/config.go
- go/config/config_test.go
- go/config/resolver.go
- go/config/resolver_test.go
- go/spec/absolute_path.go
- go/spec/spec.go
- go/spec/spec_test.go
- go/types/struct.go
- js/noms/src/spec-test.js
- js/noms/src/spec.js
- samples/go/poke/main_test.go
This is a side-by-side port, taking inspiration from the old dataspec.go
code. Notably:
- LDB support has been added in Go. It wasn't needed in JS.
- There is an Href() method on Spec now.
- Go now handles IPV6.
- Go no longer treats access_token specially.
- Go now has Pin.
- I found some issues in the JS while doing this, I'll fix later.
I've also updated the config code to use the new API so that basically
all the Go samples use the code, even if they don't really change.
> Port new Spec API to Go from JS

- samples/js/counter/package.json
Change removes dependency on bash, pushd/popd breaks installation when installing in a non bash env
> Remove dependency on bash shell from package

- js/noms/package.json
- js/noms/src/browser/fetch.js
- js/noms/src/fetch.js
- js/noms/src/http-batch-store.js
- js/noms/src/http-error-test.js
- js/noms/src/http-error.js
- js/noms/src/noms.js
I renamed HTTPError to HttpError for consistency with HttpBatchStore
(and XMLHttpRequest).
> Export HttpError and SpecOptions to Noms JS API

- tools/roll.py
If you want to roll just the go/ directory of noms, you can do:
$ roll.py https://github.com/attic-labs/noms --subdir go
Or, the nacl/secretbox/ directory of https://go.googlesource.com/crypto:
$ roll.py https://go.googlesource.com/crypto --subdir nacl/secretbox
> Add --subdir argument to roll.py

- go/types/blob.go
- go/types/indexed_sequences.go
- go/types/meta_sequence.go
- go/types/ordered_sequences.go
- go/types/sequence_cursor.go
- go/types/sequence_iterator.go
- go/types/sequence_iterator_test.go
- go/types/sequence_readahead.go
- go/util/math/minmax.go
This change implements read-ahead in the sequence_cursor to speed up sequence reads.
Some before and after numbers reading sf-registered-businesses/raw:
| Origin | Before | After |
| --- | --- | --- |
| ldb | 45 MB/s | 60 MB/s |
| localhost | 7.5 MB/s | 27 MB/s |
| demo.noms.io | 140 KB/s | 2.1 MB/s |
The approach:
For each meta-sequence that contains leaf sequences, start reading ahead in
parallel and deliver in order to a buffered channel. Each advance of the cursor gets
the next sequence in the read-ahead channel.
Since this is operating on the sequence_cursor, it benefits all sequence types.
> Improve sequence read performance using read-ahead

- go/types/sequence_iterator_test.go
PR @zcstarr: reduced the test sequence sizes to speed up tests.
> Reduce time required by sequence_iterator_test by using smaller chunk sizes

- js/noms/.flowconfig
- js/noms/package.json
- js/perf/package.json
- samples/js/package.json
This is to prevent errors in the future when the code and flow version
do not match.
> Lock down Flow version

- go/marshal/encode.go
This change addresses race conditions revealed by a segfault while running photo-dedup in production. 
The root of the problem is described in #2849. The fix is to add use a RWMutex to block encoder function calls until the function is fully initialized. 
I've verified the fix by running photo-dedup under the race detector before and after. The race is detected in the before run and is gone in the after run.
An improvement over this fix would be to implement a fast path using an atomic int (see the sync.Once.Do() implementation for an example). 
-
toward: #2849
> Fix race conditions in encoder to address photo-dedup segfault

- samples/cli/nomsconfig/.nomsconfig
when you run 
noms config
in the directory samples/cli/nomsconfig 
you get the following error message.
error: Near line 11 (last key parsed 'db.temp.url'): Strings can not contain new lines...
line 11 and line 15 need quotes at the end of the line...
> fix .nomsconfig error: Near line 11

- cmd/noms/noms_show.go
- cmd/noms/noms_show_test.go
If you want that, do `noms show <thing>@type`.
Fixes #2694
> noms show no longer shows type information

- go/nbs/compact.go
- go/nbs/compact_test.go
- go/nbs/file_manifest.go
- go/nbs/file_manifest_test.go
- go/nbs/mem_table.go
- go/nbs/mmap_table_reader.go
- go/nbs/mmap_table_reader_test.go
- go/nbs/store.go
- go/nbs/table.go
- go/nbs/table_manager.go
- go/nbs/table_reader.go
- go/nbs/table_writer.go
Encode chunk counts consistently as uint32 until #2873 is addressed. This also fixes an error in passing chunkCounts resulting from compaction that don't account for dropped (duplicate) chunks.
> uint32ChunkCount

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
Marshaling from `*types.Type` produces a noms type:
```
type S struct { Type *types.Type }
go := S{ types.String }
noms := types.NewStruct("S", types.StructData{"type": types.String})
v, err := marshal.Marshal(go) 
assert.Equals(t, noms, v)
```
Unmarshaling to `*types.Type` produces a pointer to an instance of the value:
```
type S struct { Type *types.Type }
noms := types.NewStruct("S", types.StructData{"type": types.String})
go :=  S{ types.String }
var s S
err := marshal.Unmarshal(v, &s) 
assert.Equals(t, go, s)
```
fixes: #2889
> Support marshaling from and unmarshaling to *types.Type

- go/chunks/chunk.go
- go/chunks/chunk_serializer.go
- go/chunks/dynamo_store.go
- go/chunks/leveldb_store.go
- go/datas/put_cache.go
- go/datas/serialize_hints.go
- go/diff/patch.go
- go/hash/hash.go
- go/hash/hash_slice_test.go
- go/hash/hash_test.go
- go/nbs/benchmarks/data_source.go
- go/nbs/file_manifest_test.go
- go/nbs/root_tracker_test.go
- go/nbs/store.go
- go/nbs/table_test.go
- go/types/codec.go
- go/types/get_hash_test.go
- go/types/opcache.go
- go/types/path_test.go
- go/types/rolling_value_hasher.go
- go/types/type_cache.go
- go/util/sizecache/size_cache_test.go
- js/noms/package.json
- js/noms/src/chunk.js
- js/noms/src/hash-test.js
- js/noms/src/hash.js
- js/noms/src/type-cache.js
Define the hash.Hash type to *be* a 20-byte array, rather than embed one. Also remove the `DigestSlice` function and prefer just directly taking a slice of the value.
> Minor rework of hash.Hash API

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
marshal.Unmarshal(): introduce omitempty and original support
Fixes #2795
Fixes #2796
> marshal.Unmarshal(): introduce omitempty and original support

- go/types/map.go
- go/types/map_test.go
- go/types/set.go
- go/types/set_test.go
These get the set/map element at a specific index.
I haven't implemented it in JS yet because the JS code has no method to
create a cursor at an index. This exists in Go because a refactor was
done a few months ago to add it, but it hasn't been ported to JS.
> Implement Set.At and Map.At in Go

- samples/go/blob-get/blob_get.go
- samples/go/blob-get/blob_get_test.go
I'd like to use blob-get to print string blobs directly to stdout. Here's a proposed change to make that happen.
> Make blob-get print to stdout if there is no file arg

- go/nbs/table.go
- go/nbs/table_reader.go
- go/nbs/table_writer.go
Revert to verifying chunks using the suffix index. Replace the inline 4-byte suffix used as integrity check with a more standard and efficient CRC32.
Fixes #2875
> Verify chunks using suffix index not computing address from data.

- doc/spelling.md
- go/types/path.go
- go/types/path_test.go
This lets you do foo.bar@at(n) to get the nth element of a list, set, or
map (for lists, this is equivalent to foo.bar[n]). This patch also adds
support for negative indices to @at(-n) and [-n] to get the nth element
relative to the back of collections.
> Add path @at for positional indexing, and negative indices

- samples/go/photo-date-dedup/main.go
- samples/go/photo-date-dedup/main_test.go
- samples/go/photo-index/main.go
- samples/go/photo-index/main_test.go
photo-index: output PhotoGroup instead of Photo.
This will allow UIs to display duplicate photos. Also, simplify design by creating groups even when the group has one item.
This change also maintains the old behavior via a flag so that the UI can keep working until it is updated.
> photo-index: output PhotoGroup instead of Photo

- js/noms/package.json
- js/noms/src/value-decoder.js
When we read a chunk and create structs we were validating that the
struct was of the type it claimed to be.
This now, no longer does that validation, which matches Go.
> JS: Do not validate struct type when reading a chunk

- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/indexed-sequence.js
- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/ordered-sequence.js
- js/noms/src/sequence-test.js
- js/noms/src/sequence.js
- js/noms/src/set.js
Adds the ability for `SequenceCursor`s to eagerly load all child sequences when the first child is requested.
The effect is for uses where noms tends to forward scan, it will read in batches of ~150 chunks (e.g. ~512k) rather than one chunk at a time.
On my MBP, this improves the raw blob read perf over http from ~60K/s to ~5MB/s.
Fixes #2853
> Add simple read ahead for JS Collections

- go/nbs/s3_fake_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
- go/nbs/store.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Add an S3 tableIndex cache and allow AWSStoreFactory to create a cache which is sharable across stores.
fixes #2948
> Add s3 tableIndex cache

- go/nbs/table_set_test.go
Leaving these open can leak file handles
> Close some NBS tableSets during testing

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
Currently unexported fields refuse to marshal or unmarshal, even if
they're told to skip. Now, they can be skipped. By default, they are
still errors.
> Allow skipping invalid fields when marshalling

- go/marshal/decode.go
- go/marshal/decode_test.go
This is a breaking change!
We used to create empty Go collections `[]int{}` when unmarshalling an
empty Noms collection onto a Go collection that was `nil`. Now we keep
the Go collection as `nil` which means that you will get `[]int(nil)`
for an empty Noms List.
Fixes #2969
> Marshal: Use nil for empty Go collections

- go/marshal/decode.go
- go/marshal/decode_test.go
This is a potentially breaking change!
Before this change we required all the fields in a Go struct to be
present in the Noms struct when we unmarshal the Noms struct onto the
Go struct. This is no longer the case, which means that all fields in
the Go struct that are present in the Noms struct will be copied over.
This also means that `omitempty` is useless in Unmarshal and it has been
removed.
This might break your code if expected to get errors when the field
names did not match!
Fixes #2971
> Marshal: Be more lenient when unmarshal a struct

- go/marshal/decode.go
- go/marshal/decode_test.go
This reverts commit b64f1d5dc936935f79718fe6a1b75b9a6b1af89b.
Reason: It is breaking samples/go/photo-index
Reopens: #2971
> Revert "Marshal: Be more lenient when unmarshal a struct (#2975)"

- go/nbs/benchmarks/block_store_benchmarks.go
- go/nbs/benchmarks/main.go
- go/nbs/compacting_chunk_source.go
- go/nbs/frag/main.go
- go/nbs/mem_table.go
- go/nbs/mem_table_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
- go/nbs/store.go
- go/nbs/table.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
- go/nbs/table_test.go
GetMany() calls can now be serviced by <= N goroutines, where N is the number of physical reads the request in broken down into.
This patch also adds a `maxReadSize` param to the code which decides how to break chunk reads into physical reads, and sets the s3 blockSize to 5MB, which experimentally resulted to lower total latency.
Lastly, some small refactors.
> Parallel s3 Slice reads

- doc/spelling.md
- go/chunks/dynamo_store.go
- go/nbs/benchmarks/main.go
- go/spec/spec.go
- go/spec/spec_test.go
The new spec is a URI, akin to what we use for HTTP It allows the
specification of a DynamoDB table, an S3 bucket, a database ID, and a
dataset ID: aws://table-name:bucket-name/database::dataset
The bucket name is optional and, if not provided, Noms will use a
ChunkStore implementation backed only by DynamoDB.
> Add new spec for nbs-aws

- go/chunks/chunk_store.go
- go/chunks/dynamo_store.go
- go/chunks/leveldb_store.go
- go/chunks/memory_store.go
- go/datas/local_batch_store.go
- go/datas/remote_database_handlers.go
- go/hash/hash_slice.go
- go/nbs/benchmarks/block_store_benchmarks.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
- go/nbs/block_store_test.go
- go/nbs/compacting_chunk_source.go
- go/nbs/frag/main.go
- go/nbs/mem_table.go
- go/nbs/mem_table_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_reader.go
- go/nbs/store.go
- go/nbs/table.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
- go/nbs/table_test.go
Adds the ability to stream individual chunks requested via GetMany() back to caller.
Removes readAmpThresh and maxReadSize. Lowers the S3ReadBlockSize to 512k.
Fixes #2981
Fixes #2980
> [NBS] Implement Streaming GetMany

- go/datas/http_batch_store.go
- go/datas/remote_database_handlers.go
- go/nbs/s3_table_persister.go
Relevant to: https://github.com/attic-labs/noms/issues/3006.
Ups the response-header timeout to 4m, and adds some additional log output which hopefully will shed some light on why some writes are taking so long.
> Address write timeout

- go/datas/remote_database_handlers_test.go
The order of returned chunks is no longer guaranteed.
> TestHandleGetRefs

- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/encoding-test.js
- js/noms/src/indexed-sequence-diff.js
- js/noms/src/indexed-sequence.js
- js/noms/src/list-test.js
- js/noms/src/list.js
- js/noms/src/map-test.js
- js/noms/src/map.js
- js/noms/src/meta-sequence-test.js
- js/noms/src/meta-sequence.js
- js/noms/src/noms.js
- js/noms/src/ordered-sequence-diff-test.js
- js/noms/src/ordered-sequence-diff.js
- js/noms/src/ordered-sequence.js
- js/noms/src/path.js
- js/noms/src/sequence-chunker.js
- js/noms/src/sequence.js
- js/noms/src/set-test.js
- js/noms/src/set.js
- js/noms/src/value-decoder.js
- samples/js/splore/src/main.js
Fixes #2904 and lays some ground work for lazy sequence decoding.
In particular, removes `IndexedSequence` and `OrderedSequence`. What remain are `MetaSequence` and each of the leaf sequences which directly inherit from `Sequence`.
> Js sequence refactor

- go/types/validating_batching_sink.go
- go/types/value_store.go
- go/types/value_store_test.go
- js/noms/package.json
- js/noms/src/value-store-test.js
- js/noms/src/value-store.js
Prior to this patch, ValueStore only kept a record of where referenced `Refs` originally reside in from chunks read from the server. This ignored the case of a client doing subsequent commits with the same ValueStore (for example, writing multiple states of a map). This was resulting in the server being forced to load a ton of chunks to validate.
> Remember hints for written chunks

- go/marshal/encode_test.go
- go/types/assert_type_test.go
- go/types/struct.go
- go/types/struct_test.go
- js/noms/package.json
- js/noms/src/struct-test.js
- js/noms/src/struct.js
We used to use isSubtype but we should just create a more specific type
when we can.
Fixes #2993
> Type accretion for struct fields should use equal

- go/types/value_store.go
Avoid calling batch_store.GetMany with 0 hashes.
TBR @cmasone-attic
> fix bug in ReadManyValues

- go/types/sequence_cursor.go
The issue is that iter() using readAheadLeafCursors is tied to whether a cursor is created with the `readAhead` flag. However, readAhead flags can *never* be set of "leaf" cursors.
Check the flag on parent cursor instead (if there is no parent, its fine since readAhead wont do anything).
TBR @ehalpern
> Fix bug in read ahead for sequence.iter

- js/noms/package.json
- js/noms/src/version.js
We are using babel-plugin-transform-inline-environment-variables which
replaces `process.env.FOO` with the value of the `FOO` environment
variable at compile time.
However, due to our pipeline we end with something like:
```js
var NAME = 'NOMS_VERSION_NEXT';
process.env[NAME]
```
which does not get replaced in development mode. If it was a const the
transformer could replace it but var bindings can change.
> Work around environment variable issue.

- go/datas/http_batch_store.go
- go/datas/http_batch_store_test.go
In httpBatchStore.GetMany(), we check our unwritten
puts to see if any of the requested chunks already
exist locally. If any do, we're _supposed_ to remove
their hashes from the set slated to be requested from
the server. That logic was borked.
Fixes https://github.com/attic-labs/attic/issues/503
> Only request remaining hashes in httpBatchStore.GetMany()

- js/webpack-config/index.js
- js/webpack-config/package.json
Make sure we replace process.env.NOMS_VERSION_NEXT for webpack builds
> webpack-config: Pick up noms version next

- go/types/blob.go
- go/types/collection.go
- go/types/list.go
- go/types/map.go
- go/types/set.go
- go/walk/walk.go
- go/walk/walk_test.go
This re-implements walk.Walk to traverse "down" prolly trees, loading entire subsequent levels with large batches of ReadManyValues.
> Parallelize walk.Walk

- go/util/datetime/date_time.go
- go/util/datetime/date_time_test.go
This allows us to consistently marshal back and forth between time.Time
and a Noms struct.
Fixes #2970
> Add DateTime util struct

- go/datas/remote_database_handlers.go
I'm unsure how to test that this actually affects the attic client. @arv?
Fixes: #3096
> add 1-year Cache-Control: max-age to /getBlob/ urls

- go/diff/diff.go
- go/types/map.go
- go/types/set.go
The only thing that wants what we used to call the "best" diff
algorithm is the command-line tools. Non-interactive programs all want
the algorithm that finishes up fastest, which is top-down.
Fixes https://github.com/attic-labs/attic/issues/627
> Switch Map/Set Diff to use top-down by default

- go/types/walk.go
- go/types/walk_test.go
This patch adds a static function which can walk graphs looking for (and diffing) two structs. It uses type information to avoid traversing sub-values which can't contain structs. It also uses a similar approach as sync to avoid visiting common sub-chunk-graphs.
> Introduce walk.WalkDifferentStructs

- go/nbs/block_store_test.go
- go/nbs/store.go
This code initially panicked in this case, because there didn't used
to be a reasonable way that a caller might wind up trying to update
away from a Root that didn't match NomsBlockStore's internal
bookkeeping. Now, given the new Flush() behavior there is. So, just
return false and allow the caller to take appropriate action.
Towards #3089
> NBS UpdateRoot() returns false when last != nbs.Root()

- js/noms/package.json
- js/noms/src/chunk-serializer.js
- js/noms/src/remote-batch-store.js
- js/noms/src/value-store-test.js
- js/noms/src/value-store.js
* Fixes a long standing bug in which the RemoteBatchStore is accidentally caching all chunks
* ValueStore's value cache now stores `Promise<?Value>` so that concurrent `readValues` of the same value can share a single decoding
* Removes the debug-only chunk hash check which keeps tripping up perf investigations
> Fix cache/value store caching

- tools/run_pr_builder.sh
This reverts commit 6b5e8dad0d91d713e1f6fea11e5f531e0f37db96.
Still happening...
> Revert "Update run_pr_builder.sh"

- go/ngql/query_test.go
- go/ngql/types.go
We need to fully map the noms types into graphql even though the mapping isn't useful, otherwise the endpoint may die when attempting to create a schema for types that aren't mapped.
Note the reference the proposed *real* solution for implementation once we're convinced this will all work now.
For now, Blobs & Types just get returned as a string representation of their hash value.
Also, a few more type naming cleanups
> Graphql empty collections and types

- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
Add support for unions containing scalar values by "boxing" those scalars in that context. Also add a `hash` field to Struct so that empty structs have at least one field
> Union of scalar and empty struct

- js/noms/package.json
- js/noms/src/http-batch-store.js
When we do a writeValue or updateRoot we do a POST with a request body
of some binary data. Some clients (RN) do not set the content-type
header which then leads to failure on our server.
> Add missing content type header to writeValue/updateRoot

- samples/js/counter/README.md
Delimiter should be `::` instead of `:`.
If not, it returns below error.
$ node . http://localhost:8000:counter
SyntaxError: Missing :: separator between database and dataset: http://localhost:8000:counter
at splitAndParseDatabaseSpec (/home/sungguklim/work/src/github.com/attic-labs/noms/samples/js/counter/node_modules/@attic/noms/dist/commonjs/specs.js:335:11)
at Function.parse (/home/sungguklim/work/src/github.com/attic-labs/noms/samples/js/counter/node_modules/@attic/noms/dist/commonjs/specs.js:165:35)
at main$ (/home/sungguklim/work/src/github.com/attic-labs/noms/samples/js/counter/dist/main.js:37:36)
at tryCatch (/home/sungguklim/work/src/github.com/attic-labs/noms/samples/js/counter/node_modules/regenerator-runtime/runtime.js:64:40)
> Fix typo from counter sample README.md

- go/types/simplify.go
- go/types/simplify_test.go
- go/types/type_cache.go
Implements full unions building off of makeSimplifiedUnion.
The difference between simplified unions and full unions are
in how structs are handled. In the former, we produce the intersection
of input structs to ensure the simplified type is a supertype of the input
types. In the later, we produce the union of the input structs which leads
to a type that is a subtype of all inputs.
fixes: #3204
> Implement `unionTypes(a, b *types.Type) *types.Type` (#3204)

- go/types/list.go
- go/types/map.go
- go/types/set.go
Since these functions return a receive-only channel, the
caller _can't_ close the channel it pulls the constructed
collection off of. Since the builder function can easily
know when it's safe to close the channel, it seems fine
to just have NewStreamingWhatever() do the close.
> Close output channels in streaming collection builders

- go/nbs/store.go
While it's reasonable to take out the automatic directory
creation for paths that the user types, I think we want the
factory to always be able to use the paths that it authors
underneath the directory the user passed in.
> Fix NBS LocalStoreFactory

- go/ngql/query_test.go
- go/ngql/types.go
When using keys it is possible that the key is not present. If that is
the case the value we return is null.
> GraphQL: Map values can be null when using keys arg

- go/ngql/types.go
- go/types/set_iterator_test.go
When doing a query like
```graphql
values(count:1)
```
We used to do a read ahead. This removes that read ahead.
Towards #3236
> GraphQL: Do not do read ahead when count is 1

- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
- go/util/datetime/date_time.go
- go/util/datetime/date_time_test.go
This allows go structs to participate in the MarshalType flow even
when they implement the Marshaler interface or if they have an original
tag.
> Add TypeMarshaler interface

- go/ngql/query_test.go
Instead compare the logical value the JSON represents
> Make GraphQL tests not depend on JSON serialization

- go/ngql/query_test.go
- go/ngql/types.go
This is needed because we do not have optional fields in noms structs.
Therefore the noms struct type has the field but the the noms struct may
not have it.
> Make GraphQL struct fields nullable

- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
We already had a way to generate GraphQL output types from Noms types
but no way to do input types. Input types are used in arguments
position.
We currently do not do any conversion from the JSON like data in
argument position. We leave it to the users to determine if they want
to convert the data into noms data structures or go to Go structures
or operate directly on the JSON like data.
> Noms type to GraphQL input types

- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
This exports a few functions so that we can pass variables into
the query:
- NewRootQueryObject (was constructQueryType)
- GetTypeName
- GetInputTypeName
- InputToNomsValue (was argToNomsValue)
> Expose more functions of ngql

- go/nbs/s3_table_reader.go
Run the `ss` tool in the background when issuing an S3 request. Only print its output when reading data from S3 fails, though. Also retry reads that fail in this way
> Add network connection logging

- go/nbs/s3_table_reader.go
This reverts commit 1b439af7ffc35f80b7983a8bfe26a59c52447175.
We're getting a "too many open files" issue with this `ss` tool
> Revert "Add network connection logging (#3266)"

- go/nbs/s3_table_reader.go
Trying to run `ss` in a background process on every request wound up
opening too many FDs. This is because, in order to read stderr and
stdout from the child process, the server process needed to open a
couple of pipes. For every single one. Unless they exited VERY
fast, that means that there'd be many of these child processes alive
at the same time, each requiring 2 FDs -- and this is in addition to
the incoming network connections the server is handling and all its
connections to S3.
Whoops.
This patch only spins up `ss` in the event that a request has already
failed during read. The downside is that we're getting a snapshot from
_after_ the failure. The upside is that it's likely to actually
function! The hope is that the situation that lead to the read failing
persists long enough …
> Land simpler network connection logging for #3255

- go/nbs/s3_table_reader.go
This reverts commit 151521610e617c0156a649c73dcf2f2e76149ed6.
This logging didn't provide any further insight into #3255 :-/
> Revert "Land simpler network connection logging for #3255"

- go/chunks/chunk_store.go
- go/chunks/dynamo_store.go
- go/chunks/memory_store.go
- go/chunks/test_utils.go
- go/datas/http_batch_store_test.go
- go/datas/local_batch_store.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- go/nbs/block_store_test.go
- go/nbs/store.go
- go/types/validating_batching_sink.go
- go/types/validating_batching_sink_test.go
This was something that evolved from the way that Dynamo stores
data, and a way to allow clients to make incremental write
progress. We never actually made the clients handle it
properly, though, and so much has changed since we wrote it
that it's only going to be in the way of building something
better.
Fixes #3234
> Remove ChunkStore backpressure mechanism

- go/nbs/s3_table_reader.go
Apparently, not all failures while reading get translated to
an ErrUnexpectedEOF. In order to figure out what error we see
in practice in s3_table_reader.go, log the type.
> Log error type when S3 reads fail

- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
A connection reset doesn't get caught by io.ReadFull and converted to
an io.ErrUnexpectedEOF like I thought.  So, I need to try to type
assert the error I get to *net.OpError and then use that to see if it
was a connection reset.
Workaround for #3255
> Test for the correct kind of error in s3_table_reader.go

- go/marshal/encode.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
Instead of failing. Fixes https://github.com/attic-labs/noms/issues/3284
> Skip "original" field when marshaling type

- go/ngql/query_test.go
- go/ngql/types.go
If the GraphQL schema expects a List we also allow a Set.
> NGQL: Add work around for using a Set as a List

- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
My mistake was assuming that, when a network read error happens, the
Err field of the resulting net.OpError would directly contain a
unix.Errno. What actually happens is that there's an *os.SyscallError
in there, which is the thing that's actually wrapped around the
unix.Errno. Hence, my `IsConnReset()` function was always returning
false.
This patch has been tested in the field, so I'm confident it will
work to mitigate #3255 in practice.
> One more level of error unwrapping in s3_table_reader.go

- README.md
The hyperlink points to an import statement on the master branch. By using the v7 tag in the URL, the URL will point the the intended location.
> Fix v7 hyperlink in README.md

- README.md
I attempted to build and install noms in Windows and encountered the following error:
```
C:\Users\sam\go\src\github.com\attic-labs\noms\cmd>go install ./...
..\go\nbs\file_manifest.go:46: undefined: unix.Flock
..\go\nbs\file_manifest.go:46: undefined: unix.LOCK_EX
..\go\nbs\file_manifest.go:155: undefined: unix.Flock
..\go\nbs\file_manifest.go:155: undefined: unix.LOCK_EX
..\go\nbs\mmap_table_reader.go:67: undefined: unix.Mmap
..\go\nbs\mmap_table_reader.go:67: undefined: unix.PROT_READ
..\go\nbs\mmap_table_reader.go:67: undefined: unix.MAP_SHARED
..\go\nbs\mmap_table_reader.go:82: undefined: unix.Munmap
..\go\nbs\s3_table_reader.go:131: undefined: unix.ECONNRESET
```
I believe the ability to build on Windows was broken in commit …
> Remove Windows instructions from README.md

- go/types/simplify.go
- go/types/simplify_test.go
- go/types/type_cache.go
This is needed by attic and it uses internal APIs so it has to be
exported 😢
A better path forward would be to fully implement intersection types
but that is a large change for an edge case feature.
> Resurrect MakeUnionType2 as MakeUnionTypeIntersectStructs

- go/types/simplify.go
- go/types/simplify_test.go
- go/types/type_cache.go
We ran into an issue where we passed non flatten types to simplify types
which lead to us having two `struct Commit` in a union.
> Make sure we flatten unions before calling simplify types

- go/types/type_cache_test.go
- go/types/type_desc.go
- go/types/type_test.go
We were not enforcing the order between two cycle types. In other words
the following two should be equal:
```
Cycle<0> | Cycle<1> = Cycle<1> | Cycle<0>
```
> Fix union ordering between two cycle types

- go/types/simplify.go
- go/types/simplify_test.go
Pull out the code that computes the struct fields so we can reuse
to mutate an existing struct type.
> Refactor simplifyStruct

- go/marshal/encode.go
- go/types/simplify.go
- go/types/simplify_test.go
- go/types/struct.go
- go/types/type_cache.go
- go/types/type_desc.go
- go/types/value_decoder.go
- go/types/value_encoder.go
- vendor/github.com/fatih/structs/structs.go
To contain struct name and field names.
This is in preparation for removing types from the value.
Towards #3324
> Update struct in memory representation

- cmd/noms/noms_log.go
- go/util/datetime/date_time.go
- go/util/datetime/date_time_test.go
These changes were necessary to add DateTime structs to Commit structs in attic.
> Add datetime.IsZero() and DateTimeNow() functions

- go/types/encode_human_readable.go
- go/types/simplify.go
When we clone it is possible to run into loops between named and
unnamed structs. We need to stop cloning the type tree when we see
cycle.
Also update Describe to print the actual type tree, even if it is
invalid.
> Fix issue with ilooping with unnamed structs

- go/nbs/block_store_test.go
- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/file_manifest.go
- go/nbs/file_manifest_test.go
- go/nbs/file_table_persister.go
- go/nbs/manifest.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/store.go
- samples/go/hr/test-data/manifest
Introduce a "lock" hash into NBS manifests to address the bad
interaction between Flush() and optimistic locking. Our original
design didn't include Flush(), which changes the set of tables without
updating the root. Thus... an optimistic locking strategy predicated
on checking the currently-persisted root hash is not robust to
interleaved Flush() calls from multiple clients.
Fixes #3349
> Fix NBS optimistic locking

- go/nbs/dynamo_manifest.go
Turns out 'lock' is a reserved word for DynamoDB attributes,
so change it.
> Rename 'lock' attribute in dynamo_manifest.go

- go/types/type.go
- go/types/type_cache.go
- go/types/value_decoder.go
- go/types/value_encoder.go
ValueEncoder was encoding any repeated struct name as a cycle. It needs to only do this with non-empty names.
Sorry for not catching this in review, @arv. I blame the rats.
> correctly encode struct cycles

- go/constants/version.go
- go/ngql/query_test.go
- go/types/codec.go
- go/types/codec_test.go
- go/types/list_test.go
- go/types/map_test.go
- go/types/number_util.go
- go/types/set_test.go
- samples/go/hr/test-data/manifest
Our Number encoding consists of two parts. Firsts we convert the float
into f * 2**exp, then we uvarint encode f and exp. However, we didn't
normalize f so in theory we could end up with multiple representations
of the same number.
This changes the representation to make the f the smallest possible
integer that fulfills the formula above.
For example we used to encode 256 as (0x100, 0) but with this we instead
encode it as (0x01, 8).
Fixes #2307
> Normalize our number encoding

- go/types/value_store.go
The last patch did this in order to allow bad-behavers
to still have a chance of succeding if they write Values
top down. This ensures that they won't, and therefore
will run afoul of lazy completeness checking.
Follow on for #3371
> Don't read chunk during ValueStore.bufferChunk()

- go/nbs/mem_table.go
- go/nbs/table.go
- go/nbs/table_persister.go
- go/nbs/table_reader.go
At one point, we had some hard-to-diagnose failures
decoding chunks. We tracked the problem down and fixed
it, but it's good to keep the error reporting. It's done
more cleanly and efficiently, now.
Fixes #3148
> NBS: clean up chunk extract error reporting

- cmd/noms/noms_log.go
- go/util/datetime/date_time.go
- go/util/datetime/date_time_test.go
This results in us inheriting all the methods of DateTime automatically.
> Define DateTime using struct embedding rather than type renaming.

- cmd/noms/noms_root.go
- go/chunks/chunk_store.go
- go/config/resolver.go
- go/datas/completeness_checker.go
- go/datas/database_common.go
- go/nbs/root_tracker_test.go
You can't fully specify RootTracker without referring to the
ChunkStore interface, so they should just merge.
Fixes #3402
> Merge chunks.RootTracker interface into chunks.ChunkStore

- go/nbs/block_store_test.go
- go/nbs/table.go
- go/nbs/table_persister.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Fixes #3378 
This patch changes the strategy for which tables to compact. Choose 2 or more of the N smallest tables such that the resulting table will the smallest (or tied for smallest) table in the store.
> implement "rollUp" minor compaction

- go/datas/commit.go
- go/perf/codec-perf-rig/main.go
- go/types/struct.go
- go/types/struct_test.go
- go/util/datetime/date_time.go
- samples/go/csv/csv-import/importer.go
- samples/go/csv/read.go
- samples/go/csv/read_test.go
- samples/go/csv/write_test.go
`types.MakeStructTemplate` creates a "template" whose struct & field names have been validated. It allows cases of rapidly creating struct with the same names/fieldNames to avoid the cost of allocating a map for passing field data and validating names.
Fixes #3347
> Add types.MakeStructTemplate

- go/chunks/chunk_serializer_test.go
- go/chunks/chunk_store.go
- go/chunks/chunk_store_common_test.go
- go/chunks/chunk_test.go
- go/chunks/memory_store.go
- go/chunks/memory_store_test.go
- go/chunks/test_utils.go
- go/datas/caching_chunk_haver_test.go
- go/datas/commit_test.go
- go/datas/completeness_checker_test.go
- go/datas/database_common.go
- go/datas/database_test.go
- go/datas/dataset_test.go
- go/datas/http_chunk_store_test.go
- go/datas/pull_test.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- go/perf/codec-perf-rig/main.go
- go/perf/suite/suite.go
- go/spec/absolute_path_test.go
- go/spec/spec.go
- go/types/incremental_test.go
- go/types/list_test.go
- go/types/validating_decoder_test.go
- go/types/value_store.go
- go/types/value_store_test.go
- go/types/walk_test.go
- samples/go/csv/read_test.go
- samples/go/csv/write_test.go
- samples/go/nomdex/parser_test.go
It's important that MemoryStore (and, by extension TestStore)
correctly implement the new ChunkStore semantics before we go
shifting around the Flush semantics like we want to do in #3404
In order to make this a reality, I introduced a "persistence"
layer for MemoryStore called MemoryStorage, which can vend
MemoryStoreView objects that represent a snapshot of the
persistent storage and implement the ChunkStore contract.
Fixes #3400
> Make MemoryStore come correct

- go/datas/database.go
- go/datas/database_common.go
- go/datas/database_test.go
- go/types/value_store.go
All this really does is tell the underlying ChunkStore
to go fetch the current root from persistent storage
and drops the now-out-of-date Dataset map on the floor.
Fixes https://github.com/attic-labs/attic/issues/1157
> Add Database.Rebase()

- go/nbs/s3_table_persister.go
Don't know how much this has been an issue in practice, but
it was definitely wrong.
> s3TablePersister must pass rate limiter to compacted tables

- go/types/subtype.go
- go/types/subtype_test.go
In the case where we have an optional field that is not present we still
need to check the remaining fields.
> Subtype: Make sure we continue to test after optional

- go/nbs/file_table_persister.go
- go/nbs/file_table_persister_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/persisting_chunk_source.go
- go/nbs/persisting_chunk_source_test.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_persister_test.go
- go/nbs/s3_table_reader.go
- go/nbs/table.go
- go/nbs/table_persister.go
- go/nbs/table_persister_test.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
- go/nbs/table_writer.go
The old compaction code loaded all chunks to be compacted into memory, assembled a compacted table, and then persisted it to backing storage. The nice thing about this was that we could de-dup chunks across the compacted tables. The bad thing was that we needed to hold all the chunks in memory at once. That turned out to be a problem, so we've moved to a new strategy that calculates only the merged index for the compacted table in memory, but streams chunk data directly from old tables to the new, big table. This should be a big win on S3 at least, because it turns out that for tables with > 5MB and < 5GB of chunk data, we can actually just tell S3 to reference a range of the existing object when building a compacted table.
Fixes #3411
> Streaming Compaction

- go/metrics/histogram.go
- go/metrics/histogram_test.go
I'm generally worried about the cost of locking in metrics libraries and I'd like low-level code to be free to record high-frequency events without worrying about drain on perf. For instance, the next patch here is the NBS ChunkStore exposing a `Stats` member which surfaces a bunch of low-level metrics as `Histogram`s
My idea is that these histograms can be rolled up and used as input to more full-featured metrics abstractions when necessary.
Also, having a basic infrastructure in place, allows for low-activation-energy reporting without dealing with the stack of more sophisticated infrastructure which may need to be operating across larger scale work
cc @aboodman @ehalpern
> add sucky/shameless chromium histogram knock-off

- go/nbs/manifest.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_table_persister_test.go
- go/nbs/s3_table_reader.go
- go/nbs/table_persister.go
- go/nbs/table_reader.go
Clean up NBS cruft standing in the way of improvements:
- Unmap buffer in newMmapTableReader()
By the time this function exits, we're done with this buffer.
Hanging on to it complicates lifetime management for the file
backing the mmapTableReader, which is something I'm trying to
make simpler. So...ditch it!
- remove compactSourcesToBuffer
replace with simpler test-focused version
> Clean up NBS cruft

- go/nbs/block_store_test.go
- go/nbs/fd_cache.go
- go/nbs/fd_cache_test.go
- go/nbs/file_table_persister.go
- go/nbs/file_table_persister_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/mmap_table_reader_test.go
- go/nbs/persisting_chunk_source.go
- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
- go/nbs/store.go
- go/nbs/table.go
- go/nbs/table_persister.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
For file-backed NBS, it's important that chunkSources get closed at
some point, to free up limited resources like file descriptors.
Previously, whenever a caller compacted or rebased a tableSet, the
caller had to manually close the chunkSources that were no longer
needed. This complicates logic around retrying in the event of an
optimistic lock failure.
This patch introduces a cache for open file descriptors, which
the fsTablePersister uses to manage the lifetime of files
automatically. The fdCache ref-counts open file descriptors,
but doesn't keep a hard cap on the number of open files. Once
the cache's target size is exceeded, opening a new file causes
the cache to look for fds with zero refs to close. It closes
as many of those as needed to get back under the target size.
Towards #3462
> NBS: Remove need to manually manage chunkSource lifetime

- go/datas/remote_database_handlers.go
- go/diff/diff.go
- go/merge/candidate.go
- go/merge/three_way.go
- go/merge/three_way_ordered_sequence.go
- go/types/map_leaf_sequence.go
- go/types/map_test.go
- go/types/ordered_sequences.go
- go/types/ordered_sequences_diff.go
- go/types/ordered_sequences_diff_test.go
- go/types/set_test.go
- go/types/struct.go
- go/types/struct_test.go
And changes `.V` => `.Key`
Note that I haven't fully updated the usages of this in noms, but rather opened two bugs: 
https://github.com/attic-labs/noms/issues/3467
https://github.com/attic-labs/noms/issues/3466
> OrderedSequenceDiff ValueChanged adds NewValue/OldValue

- go/nbs/store.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Currently, we handle NBS compactions by having clients detect that one
is necessary, perform the compaction locally, and then attempt to
persist the work. The old strategy, removed in this patch, was to
abandon the work if any other client had changed anything upstream
since the compaction began. Since compaction can be slow, this
happened frequently. The new strategy is to tolerate new tables
appearing upstream as long as all the tables the client compacted
still exist. In that case, the client will now rebase against upstream
successfully, droping the tables that got compacted, and then attempt
to land the compaction once again.
Fixes #3462
> NBS: Tolerate other clients writing novel tables during compaction

- go/nbs/store.go
Turns out sometimes Put() is so fast it gets reported as
taking 0ns. It's nonsensical to put a 0 in a Histogram, so
don't. Just change it to 1.
Fixes #1787
> NBS: Don't add 0-sample to histogram in Put()

- go/util/datetime/date_time.go
Mainly putting this up for consideration, could easily put this abstraction in the consuming code.
Also not sure if there's a way to test this. Is there a way to mock a package that isn't injected in go?
> add .Now() to datetime package

- go/nbs/block_store_test.go
- go/nbs/conjoiner.go
- go/nbs/conjoiner_test.go
- go/nbs/dynamo_manifest.go
- go/nbs/factory.go
- go/nbs/file_manifest.go
- go/nbs/file_table_persister.go
- go/nbs/file_table_persister_test.go
- go/nbs/manifest.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_persister_test.go
- go/nbs/stats_test.go
- go/nbs/store.go
- go/nbs/table_persister.go
- go/nbs/table_persister_test.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Previously, every NomsBlockStore instance decided when to conjoin
tables (and which to conjoin) entirely on its own, which led to A LOT
of concurrent conjoining that would mostly be wasted effort, as one
instance would win the race and then all the rest would drop their
work on the floor, rebase, and continue. This patch introduces a
'conjoiner' that is either process-global, or owned by one of the NBS
factory objects you can create. Now, NBS instances vended by a given
factory call this single conjoiner during Commit(), asking it to
perform a conjoin if necessary. If a conjoin is already underway, the
conjoiner blocks the caller until it's finished and then
returns. Whether the conjoin was triggered at the caller's request, or
the caller got to opportunistically piggyback on a conjoin …
> NBS: Avoid concurrent (in-process) conjoins to a given store

- go/nbs/factory.go
- go/nbs/store.go
Thinking more about it, there's no current need for a consumer to *set* max tables for the file backend (one could imagine it for tuning purposes, but we're not there). However, we now have a more meaningful control over max open file handles, so that's now configured.
Also, while we're picking numbers of out thin air, 128 tends to keep the manifest < 1 read on dynamo, but seems a tad small for file, which has no such limit. setting file 2x as large.
> maxTable nit-picking

- cmd/noms/noms_sync.go
- cmd/noms/noms_sync_test.go
- go/chunks/chunk_store.go
- go/chunks/memory_store.go
- go/chunks/remote_requests.go
- go/chunks/remote_requests_test.go
- go/constants/version.go
- go/datas/completeness_checker.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/pull.go
- go/datas/pull_test.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- go/nbs/block_store_test.go
- go/nbs/store.go
- samples/go/hr/test-data/manifest
In an NBS world, bulk 'has' checks are waaaay cheaper than they used
to be. In light of this, we can toss out the complex logic we were
using in Pull() -- which basically existed for no reason other than to
avoid doing 'has' checks. Now, the code basically just descends down a
tree of chunks breadth-first, using HasMany() at each level to figure
out which chunks are not yet in the sink all at once, and GetMany() to
pull them from the source in bulk.
Fixes #3182, Towards #3384
> Simplify Pull()

- go/chunks/chunk_store.go
- go/chunks/memory_store.go
- go/datas/database.go
- go/datas/database_common.go
- go/datas/http_chunk_store.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
- go/nbs/stats_test.go
- go/nbs/store.go
This just returns interface{}, allowing underlying ChunkStore
implementations to return whatever kind of stats struct they want.
Fixes #3493
> Add Stats() to Database

- go/datas/database_common.go
- go/datas/dataset.go
This is kind of minor, but it's silly that db.GetDataset was reading the head value then dropping it on the floor. Instead, cache it inside Dataset rather than the ref. As a side-benefit, this also creates the `HeadRef` lazily, which is nice because it's rarely needed and the type is presently expensive to compute.
> Dataset caches HeadValue rather than HeadRef

- tools/roll.py
This makes it possible to include/exclude multiple directories
when rolling src into a vendor directory.
For example, to roll the `cmd` and `go` directories from github.com/attic-labs/noms
into your vendor directory, you could run the following:
```
cd $MY_REPO_HOME
$NOMS/tools/roll.py --incl cmd --incl go https://github.com/attic-labs/noms
```
This patch also strips '.git' if it's present on the end of the repo url.
> Modify roll.py to handle multiple --incl directories

- go/nbs/file_table_persister.go
- go/nbs/fs_table_cache.go
If one of these got left behind in a cache directory, e.g.
due to a crash, subsequent runs should tolerate and remove it
instead of panicing
> NBS: fs table cache should tolerate its own temp files

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
The main difference is that we now have to keep track of the index path
into the embedded structs.
Towards #2376
> Marshal: Add support for embedded structs

- go/marshal/encode.go
- go/marshal/encode_test.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
This is done by implementing StructNameMarshaler interface. For example
```go
type TestStruct struct {
...
}
func (ts TestStruct) MarshalNomsStructName() string {
return "HelloWorld"
}
```
Fixes #2972
> Marshal: Add a way to define the struct name

- go/marshal/encode.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
1. In MarshalType() allow Noms collections without element types, e.g.:
type Foo struct {
A types.List
}
marshal.MustMarshalType(Foo{}) => struct Foo { A List<Value> }
2. There were cases where we would fail to marshal structs containing
non-comparable Go types (e.g. slices). Fix those using DeepEqual().
> Add two small features to marshaling

- go/nbs/fs_table_cache.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_persister_test.go
- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
These tests verify that tables get cached on Perist(), and that
tableReaders vended by s3TablePersister correctly use the cache.
> NBS: Add more tests for table cache usage in s3TablePersister

- cmd/noms/noms_show.go
- go/datas/completeness_checker_test.go
- go/datas/http_chunk_store_test.go
- go/datas/remote_database_handlers_test.go
- go/types/codec.go
- go/types/compare_test.go
- go/types/encoding_test.go
- go/types/get_hash.go
- go/types/meta_sequence.go
- go/types/opcache.go
- go/types/rolling_value_hasher.go
- go/types/type_test.go
- go/types/validating_decoder_test.go
- go/types/value_encoder.go
- go/types/value_stats.go
- go/types/value_store.go
Ok, here's step one. 
Separate the concern of flushing uncommitted (linked in-memory) ptree nodes from encoding.
Towards #3525
> move flushing of uncommitted ptree nodes out of EncodeValue

- go/chunks/chunk_store.go
- go/chunks/memory_store.go
- go/nbs/dynamo_manifest.go
- go/nbs/factory.go
- go/nbs/factory_test.go
- go/nbs/store.go
Add a method to chunks.Factory that allows the caller to
signal that it's willing to try to make forward progress
using an out-of-date ChunkStore. This allows AWSStoreFactory
and LocalStoreFactory to vend NBS instances without hammering
persistent storage every time.
Towards #3491
> Add chunks.Factory::CreateStoreFromCache()

- cmd/noms/noms_root.go
- go/chunks/chunk_store.go
- go/chunks/chunk_store_common_test.go
- go/chunks/memory_store.go
- go/datas/database_common.go
- go/datas/database_test.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- go/nbs/benchmarks/block_store_benchmarks.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
- go/nbs/block_store_test.go
- go/nbs/factory_test.go
- go/nbs/root_tracker_test.go
- go/nbs/stats_test.go
- go/nbs/store.go
- go/types/incremental_test.go
- go/types/list_test.go
- go/types/map_test.go
- go/types/ordered_sequences_diff_test.go
- go/types/value_store.go
- go/types/value_store_test.go
Turns out this complicated the threadsafety goal
> Revert removal of |last| from Commit()

- go/types/sequence_chunker.go
- go/types/sequence_concat.go
Towards #2300
This refactor simplifies (and I think clarifies) the behavior of working with cursors in re-chunking a prolly tree. The logic change here is mainly in finalization. I think the way the logic worked (at least) at one point, it was possible that a child & parent cursor would become "decoupled" (i.e. the parent wasn't presently referencing the child. The chunker has been simplified recently, and I think there are no more such necessary cases.
The logic in finalization becomes alot simpler as a result. Basically, what results is that the *only* time we need to explicitly advance a parent cursor is when we have "finished" with the child.
@kalman, please review post-facto. @aboodman, please review for local correctness now.
> Don't clone cursors in sequence chunker

- go/types/sequence_chunker.go
> SequenceCursor.advanceTo shouldnt step out of parent sequence

- go/types/map.go
- go/types/ordered_sequences.go
- go/types/sequence_chunker.go
- go/types/set.go
When sequence chunker advances to a new position for streaming edits, it needs to ensure that it doesn't `resume()` over items which have already been consumed at this level.
The specific case that trigger this was making two edits to map, both of which took place within the same leaf sequence. this case can only arise when the final item in the map is an "explicit" boundary. If the first edit doesn't "change" the boundary (i.e. it will still cause the rolling hash to hit a target pattern), and the second edit is trying to append beyond the last existing element, then what happened was the code *thought* that the `next` cursor hadn't been reached and thus "resumed" at that level, but that caused it to re-consume items that were already consumed.
> sequenceChunker.advanceTo avoid resuming over items it already consumed

- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/factory.go
- go/nbs/factory_test.go
- go/nbs/file_manifest.go
- go/nbs/file_manifest_test.go
- go/nbs/manifest.go
- go/nbs/manifest_cache.go
- go/nbs/manifest_cache_test.go
- go/nbs/store.go
There were races in both manifest implementations, between cache usage
in ParseIfExists() and Update(). It was possible for Update() calls to
occur between the time that ParseIfExists() read the manifest data and
the time it updated the cache. This led to newer manifest content
getting clobbered in the cache by out-of-date manifest content.
The new approach takes caching out of the hands of the manifest impls,
instead wrapping a shared caching layer around the outside.
Fixes #3551
> NBS: Fix usage of manifestCache

- go/chunks/chunk_store.go
- go/chunks/remote_requests.go
- go/chunks/remote_requests_test.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
In httpChunkStore, calls to Get/Has and friends put a request object
with a 'return channel' onto a queue channel, and then block on the
return channel. The queue channel was buffered, which made it
impossible to cause Get, Has et al to terminate reliably when the
store was closed.
This patch removes the buffering on the channel so we can
deterministically bail from Get/Has et al when closing the store. I
don't think we were actually seeing any benefit from the buffer on the
queue channels, because everywhere we write to one of them we
immediately block on another channel, waiting for the result of the
request.
Fixes #3566
> Fix httpChunkStore race between Close() and Has/Get

- go/nbs/block_store_test.go
- go/nbs/manifest.go
- go/nbs/root_tracker_test.go
- go/nbs/store.go
If NomsBlockStore can assume that its manifest is a cachingManifest,
it can pre-emptively check to see if someone else in-process has
already moved the manifest forward and, if so, fail early.
Fixes #3574
> NBS: updateManifest() fails fast if Update is DOOOOOOMED

- go/nbs/block_store_test.go
- go/nbs/factory.go
- go/nbs/manifest.go
- go/nbs/manifest_cache.go
- go/nbs/root_tracker_test.go
- go/nbs/store.go
Prior to this patch, the manifest cache was effectively serializing all IO to the underlying manifest across a factory (i.e. multiple calls to Rebase() of different stores). This allows IO to different stores to proceed concurrently.
> add store-granularity locking to manifest cache

- go/nbs/manifest.go
- go/nbs/manifest_cache.go
- go/nbs/manifest_cache_test.go
It occurred to me that the timestamp here needs to be *pessimistic* and use the time prior to initiating the IO call in order to avoid a race.
> fix manifest cache race

- go/nbs/file_table_persister.go
- go/nbs/mmap_table_reader.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_reader.go
- go/nbs/table_persister.go
By adding per-entry locking to indexCache, this patch allows both NBS
storage backends to ensure that only one goroutine is loading a given
table index at a time. Previoudly, if multiple readers tried to open
the same table at the same time, it was possible for both to get a
cache-miss and then read in the table index at the same time, which
wastes memory.  Now, one will win the race, load the index, and then
the other will see a cache hit.
Fixes #3581
> NBS: Prevent concurrent loading of the same table index

- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
We need to use getStructName in MarshalType too.
Fixes https://github.com/attic-labs/attic/issues/2289
> MarshalType: Make sure we use the user provided name

- go/datas/http_chunk_store_test.go
- go/datas/pull_test.go
- go/datas/remote_database_handlers_test.go
- go/diff/apply_patch.go
- go/merge/three_way_list.go
- go/perf/codec-perf-rig/main.go
- go/types/list.go
- go/types/list_editor.go
- go/types/list_editor_test.go
- go/types/list_test.go
- go/types/map_editor.go
- go/types/ref_test.go
- go/util/jsontonoms/json_to_noms_test.go
This should look somewhat familiar =-).
Towards #3562. This removes the mutative API from List and adds a ListEditor which is logically consistent with the existing Set/MapEditor. BlobEditor is next and should look similar to ListEditor.
> List Editor

- cmd/noms/noms.go
- go/config/resolver.go
- go/datas/database_server.go
- go/datas/remote_database_handlers.go
- go/util/verbose/verbose.go
All messages emitted from non-cli code are now output through the standard
logger rather than directly to stdout. This gives code that embeds noms control
over how messages are logged (using log.SetFlags and log.SetOutput).
When the noms cli is used, the logger is initialized so that it only prints the
string logged. In other cases, the log setup is left to the embedding code.
toward: #3590
> Use log.PrintXXX rather than fmt.PrintXXX for informational messages

- go/datas/remote_database_handlers.go
- go/perf/codec-perf-rig/main.go
- go/types/blob.go
- go/types/blob_test.go
- go/types/indexed_sequences.go
- samples/go/blob-get/blob_get.go
- samples/go/csv/csv-import/importer.go
- samples/go/nomsfs/nomsfs.go
Towards #3562 (Next patch will be BlobReadWriter)
This patch refactors Blob reading generally:
-Add `LoadLeafSequences`, which eagerly loads exactly the set of leaf sequences which contain a given idx range
-`Blob` now supports the golang `ReaderAt` interface. The implementation uses `LoadLeafSequences` to eagerly load exactly the needed byte range
-`BlobReader` is now basically just an `int` (pos) which turns around and uses `Blob.ReadAt`
-`BlobReader.Copy` is moved to `Blob` and uses a read ahead strategy of N concurrent forward reads, but each uses `ReadAt` (rather than the less precise `readAheadLeafCursors`).
This wasn't the goal here, but a happy side-effect is that blob reading perf has generally increased:
-Reading large blob via http: +40% (now about 250MB/s on my mac)
-Reading …
> Refactor Blob reading

- go/nbs/block_store_test.go
- go/nbs/conjoiner.go
- go/nbs/conjoiner_test.go
- go/nbs/factory.go
- go/nbs/manifest.go
- go/nbs/manifest_cache.go
- go/nbs/root_tracker_test.go
- go/nbs/stats_test.go
- go/nbs/store.go
This patch uses process-wide per-store locking to ensure that only one
NomsBlockStore instance is ever trying to update the upstream NBS
manifest at a time. It also locks out attempts to fetch the manifest
contents during that window.
Conjoining is now much simpler. Since only one instance can ever be in
the critical path of Commit at a time, and conjoining is triggered on
that critical path, we now simply perform the conjoin while excluding
all other in-process NBS instances. Hopefully, locking out instances
who want to fetch the manifest contents during a conjoin won't cripple
performance.
Fixes issue #3583
> NBS: Serialize Commit() calls within a process

- go/constants/version.go
- go/datas/http_chunk_store.go
- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
- samples/go/hr/test-data/manifest
Right now, the only kinds of Commits that the server will retry are those to different datasets.
That is, if another client concurrently landed a change to some other dataset, and that is the _only_ thing that causes your Commit attempt to fail, the server will retry.
Fixes #3582
> Allow server to re-try commits if it can

- go/nbs/manifest.go
- go/nbs/store.go
Persisting tables now tacks place outside the manifest fetch lock so rebasers don't spend time blocking on writers persisting.
> NBS: Commit locks out Rebasers for less time

- go/types/collection_test.go
No need to calculate this anymore. It's encoded into the sequences
TBR @kalman
> Minor test cleanup

- go/nbs/aws_table_persister.go
- go/nbs/aws_table_persister_test.go
- go/nbs/conjoiner.go
- go/nbs/dynamo_fake_test.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/dynamo_table_reader.go
- go/nbs/dynamo_table_reader_test.go
- go/nbs/factory.go
- go/nbs/s3_table_reader.go
- go/nbs/stats.go
- go/nbs/store.go
There seems to be a floor on the amount of time required to persist
small objects to S3. For workloads that generate lots of small tables,
this can really add up. DynamoDB is much faster to read/write, and can
hold items of up to 400k. This patch stores tables with < 64 chunks
that are < 400k in DynamoDB, caching them in memory on persist and
open to reduce load on the back end.
Fixes #3559
> NBS: Store small tables in DynamoDB when persisting to AWS

- samples/go/nomsfs/README.md
Previous instructions were obsolete, but nomsfs works again if you use this location instead.
> update README for OSXFuse

- go/nbs/aws_chunk_source.go
- go/nbs/aws_chunk_source_test.go
- go/nbs/aws_table_persister.go
- go/nbs/aws_table_persister_test.go
- go/nbs/block_store_test.go
- go/nbs/conjoiner.go
- go/nbs/conjoiner_test.go
- go/nbs/dynamo_table_reader.go
- go/nbs/dynamo_table_reader_test.go
- go/nbs/factory.go
- go/nbs/file_table_persister.go
- go/nbs/file_table_persister_test.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
- go/nbs/stats.go
- go/nbs/store.go
- go/nbs/table_persister.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Prior to this patch, whenever we created a chunkSource for a table
persisted to AWS, awsTablePersister::Open() would hit DynamoDB to
check whether the table data was stored there. That's how it knew
whether to create a dynamoTableReader or an s3TableReader. This
results in consulting Dynamo (or the in-memory small-table cache)
every time we go to open a table. Most of the time, this isn't
necessary, as we separately cache table indices and really only
need that data at Open() time.
This patch defers reading table data if possible.
Fixes #3607
> NBS: Defer AWS reads when opening a table with cached index

- go/types/blob.go
- go/types/blob_test.go
- go/types/collection_test.go
- go/types/indexed_sequences.go
- go/types/util_test.go
This fixes a long standing annoyance. The collection tests now sanity check total & diff number of *leave* nodes (as opposed to root-1 level). This makes the tests much easier to reason about because how deep the tree is doesn't create discontinuities when the serialization changes.
TBR @kalman
> Collection test

- go/types/path.go
- go/types/path_test.go
Struct type field support field paths, like `.fieldName`
Compound types (List/Set/Map/Union) support index paths, like `[0]`
> Make field and index paths work for types

- go/constants/version.go
- go/sloppy/sloppy.go
- go/sloppy/sloppy_test.go
- go/types/codec.go
- go/types/compare_test.go
- go/types/encoding_test.go
- go/types/list_test.go
- go/types/map_test.go
- go/types/opcache.go
- go/types/rolling_value_hasher.go
- go/types/set_test.go
- go/types/value_encoder.go
- samples/go/hr/test-data/manifest
Introduce Sloppy - an estimating compression function for snappy - which allows for the rolling hash to better produce a given target chunk size *after compression*.
Fixes #2763, Fixes #3369
> Introduce Sloppy

- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
- go/types/map_test.go
This removes the type tagged version of the human readable encoding.
Motivation: Simplify this in preparation to make the HRS unambiguous so that we can write a parser.
Towards #1466
> Remove HRS tagged versions

- cmd/noms/noms_show_test.go
- go/diff/diff_test.go
- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
Print Ref values as `#123` instead of `123`
Since our hashes are SHA-512 and we write them using Base32 there are a lot of overlaps with other parts of NomDL. This makes them unambiguous.
Towards #1466
> Print ref with pound

- cmd/noms/noms_show_test.go
- go/diff/diff_test.go
- go/marshal/decode_test.go
- go/marshal/encode_type_test.go
- go/merge/three_way_keyval_test.go
- go/spec/commit_meta_test.go
- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
- go/types/type_test.go
For struct values we always prefix with `struct `.
For struct types we always prefix with `Struct `.
Towards #1466
> HRS: Cleanup struct head

- go/types/encode_human_readable.go
We always write the struct name now so no point in passing the
param.
> HRS: Struct printing cleanup

- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
This prints blob values as:
```
blob {  // 17 B
00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
10
}
```
Towards #1466
> HRS: Write blob values as blob { ... }

- cmd/noms/noms_show_test.go
- go/diff/diff_test.go
- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
We now print map and set values as:
```
map {
"string": 42,
"set": set {
true,
false,
},
}
```
Towards #1466
> HRS: Prefix map/set values with map/set

- go/spec/spec.go
- go/spec/spec_test.go
Tests detect error from later in function but we can catch invalid specs earlier by handling the error returned from splitDatabaseSpec
> Don't ignore spec split error in ForDatasetOpts

- go/ipfs/cs.go
- samples/go/ipfs-chat/daemon.go
- samples/go/ipfs-chat/main.go
- samples/go/ipfs-chat/model.go
- samples/go/ipfs-chat/pubsub.go
* Change ipfs paths to include directory where ipfs repo is stored.
* Rework ipfs-chat to create ipfs chunkstores manually rather than
relying on Spec.ForDataset. This enables creating two chunkstores
(one local and one network) using the same IpfsNode (ipfs repo).
* Create separate replicate function for daemon and mergeMessage
function for client to experiment with slightly different behaviors
for each.
> Modifications to ipfs-chat can ipfs chunkstore

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
By default, each column name maps to a struct field preserving the original case.
If --lowercase is specified the resulting struct fields will always be lowercase.
> Add --lowercase option to map column names to lowercase struct names

- go/nbs/frag/main.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
The new version of this tool now estimates the locality of a DB
written using the "grandchild" strategy implemented by
types.ValueStore. It does do by dividing each level of the graph
up into groups that are roughly the size of the branching factor
of that level, and then calculating how many physical reads are
needed to read each group.
In the case of perfect locality, each group could be read in a
single physical read, so that's what the tool uses as its estimate
of the optimal case.
Toward #2968
> NBS: Fragmentation tool using new estimate of locality

- samples/go/csv/csv-invert/.gitignore
- samples/go/csv/csv-invert/main.go
Takes the output of a CSV file imported as a List of Struct and
"inverts" it so that it's now a Struct of Lists.
Example:
List<Struct Row {
Base?: String,
DOLocationID?: String,
}>
becomes
Struct Columnar {
base: List<String>,
dolocationid: List<String>,
}
> `csv-invert` command line tool

- go/datas/commit.go
- go/datas/commit_test.go
- go/marshal/encode_type_test.go
- go/nomdl/parser.go
- go/nomdl/parser_test.go
- samples/go/nomsfs/nomsfs.go
This allows parsing all Noms values from the string representation
used by human readable encoding:
```
v, err := nomdl.Parse(vrw, `map {"abc": 42}`)
```
Fixes #1466
> Add support for parsing values

- go/datas/http_chunk_store_test.go
- go/types/blob.go
- go/types/indexed_sequences.go
- go/types/list.go
- go/types/list_test.go
- go/types/map.go
- go/types/map_test.go
- go/types/sequence_chunker.go
In most cases this will avoid writing the root chunk of a prolly tree,
which is the behavior we're aiming for: a prolly tree might be used
inline in which case the root never needs to be written.
The solution in this patch is imperfect because it may unnecessarily
write chunks, but this is rare.
Fixes https://github.com/attic-labs/noms/issues/3645
> Don't write a sequence chunk if there is no parent

- samples/go/nomsfs/basics_test.go
- samples/go/nomsfs/dir_test.go
- samples/go/nomsfs/nomsfs.go
- samples/go/nomsfs/rw_test.go
Fixes test errors on non darwin/linux machines.
```
FAIL  github.com/attic-labs/noms/samples/nomsfs [build failed]
src/github.com/attic-labs/noms/vendor/github.com/hanwen/go-fuse/fuse/types.go:369.2: undefined: Attr
```
> NOMSFS: only build for darwin/linux

- go/types/sequence_chunker.go
> Reuse the "current" buffer in sequenceChunker

- go/types/blob.go
- go/types/leaf_sequence.go
- go/types/list.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/ref.go
- go/types/sequence.go
- go/types/sequence_cursor.go
- go/types/sequence_cursor_test.go
- go/types/struct.go
- go/types/value_decoder.go
- samples/go/csv/write.go
This optimizes CSV export after the change in types.Value being backed
by byte slices.
Towards #3710
> Optimize CSV Export

- go/types/blob_leaf_sequence.go
- go/types/bool.go
- go/types/codec.go
- go/types/encoding_test.go
- go/types/leaf_sequence.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/number.go
- go/types/ref.go
- go/types/rolling_value_hasher.go
- go/types/string.go
- go/types/struct.go
Also make the primitives allocate a more exact buffer instead of the
initialBufferSize.
Also, stack allocate binaryNomsWriter
> Make EncodeValue return bytes directly

- go/types/leaf_sequence.go
- go/types/struct.go
- go/types/value_decoder.go
This improves csv-import a bit since it allows us to skip allocation of
values in the struct when we only want the type.
> Add readTypeOfValue

- go/types/struct.go
> Replace regexp with loop for struct name/field validation

- CONTRIBUTING.md
- README.md
- cmd/noms/README.md
- doc/cli-tour.md
- doc/decent/architectures.md
- doc/decent/demo-ipfs-chat.md
- doc/decent/demo-p2p-chat.md
- doc/decent/quickstart.md
- doc/go-tour.md
- doc/intro.md
- doc/spelling.md
- go/nbs/NBS-on-AWS.md
- go/nbs/README.md
- samples/cli/nomsconfig/README.md
- samples/go/csv/README.md
- samples/go/hr/README.md
- samples/go/nomdex/Readme.md
- samples/go/nomsfs/README.md
General cleanup to finish up the last bit of formatting on https://github.com/attic-labs/decent-website/issues/13
> Update code blocks to always specify syntax, fix ordered list

- go/types/codec.go
- go/types/struct.go
- go/types/struct_test.go
The old code was hard to follow and it ended up encoding twice when a
new field was added.
> Simplify Struct Set/Delete

- go/types/blob.go
- go/types/leaf_sequence.go
- go/types/list.go
- samples/go/csv/write.go
This copies the approach that Blob.Copy uses, with some extra logic to
adjust the number of values to read as more values are read.
> Change List.IterAll to read-ahead 8MB chunks over 6 threads

- go/datas/pull.go
- go/types/codec.go
- go/types/list_editor.go
- go/types/ref.go
- go/types/struct.go
- go/types/value_decoder.go
- go/types/walk.go
- go/types/walk_refs.go
- go/types/walk_refs_test.go
This patch introduces WalkRefs(c chunks.Chunk, cb RefCallback), which
allows the refs in a Chunk to be walked without first decoding the
Chunk into a Value. It's useful in e.g. datas.Pull(), which needs to
walk the Chunk graph, but doesn't actually care about the Values.
On my macbook, syncing e.g. a large dataset imported from a .csv file
is about 4x faster.
> Enable walking refs in a Chunk without decoding to a Value

- go/datas/pull.go
In Pull(), attempt to limit memory usage by capping the number
of chunks processed at the same time. If a given level of the
chunk graph has more than |batchSize| members, they will still
be processed in order.
Fixes #3692
> Sync: Batch up chunk processing during pull

- go/types/leaf_sequence.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/struct.go
- go/types/value_store.go
- go/types/walk_refs.go
- go/types/walk_refs_test.go
For values that are currently backed by byte-slices in memory, use `refWalker` as the implementation for `WalkRefs`. This is preferable ATM because it avoids allocating (in particular, strings in structs).
> Use refWalker for Value.WalkRefs

- go/types/list.go
- go/types/list_test.go
- go/types/sequence_cursor.go
Adds explicit API to list to iterate a range of indices. The implementation of this uses the most eager read of the required data.
> Add List.IterRange

- go/constants/version.go
- go/sloppy/sloppy.go
- go/types/blob_test.go
- go/types/list_test.go
- go/types/map_test.go
- go/types/rolling_value_hasher.go
- go/types/set_test.go
- samples/go/hr/test-data/manifest
Towards #3743 
Includes a set of changes aimed at better handling of Lists which contain long subsequences of repeated values (e.g. 1.1 Billion "yellow" strings).
Turns out a few things were happening here
1) The sloppy lookup table was only 16 bits and so when the input byte stream crossed 64k it stopped find matches. Fix: the lookup table now stores 32 bit offsets
2) "yellow" repeated encodes as patterns of 8 bytes, this (by chance) drove the rolling hash to zero from which it never recovers. Fix: make the hash window a prime value (67 bytes).
3) There already is a maxCopy in sloppy, but this effectively results in the rolling hash seeing long repeated sequences of 3 bytes (just repeats of the copy). The reduces entropy further and the input sequence never chunks (just by chance). Fix: …
> Avoid creating gigantic chunks with Lists of very long repeated values

- go/types/leaf_sequence.go
- go/types/make_type.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/ref.go
- go/types/simplify.go
- go/types/simplify_test.go
- go/types/struct.go
- go/types/type.go
- go/types/type_desc.go
- go/types/value_decoder.go
When we compute the type of a sequence we used to compute the type of
every value in the sequence and then simplify the union. Now we check
if the type of the value is the same as the type of the last element, in
which case we do not need to include it in the union. This is the common
case and it allows us top skip allocating a lot of Types and it makes
the Type to simplify smaller which makes simplifying the type faster.
Also, handle the simple cases where the type is already simplified.
Optimize `*Type` `Equals` to reduce the number of times we have to
encode it.
Introducing `makeUnionType` that removes the `Union<T>` earlier so that
there is less work to do in `simplifyType`.
This halves the amount of time spent in TypeOf for csv import, going
from 18 MB/s to 27 MB/s
Towards #3710, …
> Optimize typeOf for sequences and simplifyType

- go/constants/version.go
- go/types/encoding_test.go
- go/types/meta_sequence.go
- go/types/noms_kind.go
- go/types/value_decoder.go
- go/types/walk_refs.go
- samples/go/hr/test-data/manifest
Instead introduce a new NomsKind (called hashKind) which is internal
only.
Fixes #1688
Update version to 7.18
>  Remove hack for meta tuples of refs

- go/marshal/encode.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
- go/ngql/query_test.go
- go/util/datetime/date_time_test.go
We were caching the encoder function enclosing over the passed in
ValueReadWriter. This causes problems when the encoder is used again but
with another ValueReadWriter.
Instead, make the internal encoder function take a ValueReadWriter.
> Fix issue with marshal caching vrw

- .dockerignore
- Dockerfile
This is substantially based on https://hub.docker.com/r/scjalliance/noms/
but has been updated in two ways:
1. It uses a multi-stage build to substantially reduce the size of the
resultant image. The naive build image clocks in at ~1gb; the output
image here is ~30mb.
2. It takes advantage of the fact that the build context is already
present, so we can speed up the build process by simply copying
the context instead of cloning the data again.
This is intended to be compatible with #3790, and does not address
any of the issues mentioned there except simple creation of a dockerfile.
If the source repository for that PR were publicly available, this PR
would have targeted that branch instead of master.
> Add a multi-stage-build dockerfile

- .dockerignore
- .travis.yml
- Dockerfile
- README.md
Regarding #3792 
Wanted to start the discussion on picking the low hanging fruit here. 
- Are there any other steps that should go into CI at this point? Linting, formatting, etc.
- Is it important to run on PRs ala Travis? If so can we just run docker build as our travis script?
If we'd like to do that I'm happy to write the `.travis.yml` if someone can enable travis for the repo
Note: tests have two actual failures at this point so this will fail to build at dockerhub. Accepting this pull as is though will show that failures do get correctly reported in the badge so should perhaps proceed before fixing the two issues.
Even if we move to travis and don't use docker build as the script, which is also fine, it might be worth considering accepting this change so that we don't publish broken …
> Using Dockerhub as a basic CI

- cmd/noms/splore/noms_splore.go
- go/merge/three_way.go
- go/types/struct.go
- go/types/struct_test.go
- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-invert/main.go
As well as list and map, I would like to write the following the code by struct's iteration method.
```
var error err
str.IterFields(func(name string, value types.Value) bool {
err = SomeMethod()
if err != nil {
return true
}
return false
})
if err != nil {
return err
}
```
> Enable to stop in struct's IterFields method

- LICENSE
- README.md
Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in
https://landscape.cncf.io/selected=noms-db)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit modifies a few of Noms' docs so that Licensee is able
to recognize the repository's license type. It updates LICENSE so that
it contains the full text of the Apache license. It also updates the
README with a new "Licensing" section.
Collectively, these changes allow Licensee to successfully identify the
license type of Noms as Apache 2.0.
For comparison purposes, here is the output that I get when I run Licensee locally on Noms' remote repo:
```
$ licensee …
```
> edit Noms license info so that GitHub recognizes it

- tools/file/file.go
On FreeBSD, attempting to copy a directory using DumbCopy returns successfully.
```
--- FAIL: TestSerialRunnerTestSuite/TestNoCopyDir (0.00s)
Error Trace:     file_test.go:85
Error:              An error is expected but got nil.
```
> ensure directories aren't copied

- samples/go/json-import/json_importer.go
Now that we have simple cli manipulation tools, we no longer need the import tools to support committing on their own. You can just import, get a hash, and use that to do what you want with.
Also updated json_import to use kingpin so the cli docs are better.
> Simplify json_import

- cmd/noms/noms_struct.go
Print out only absolute path, not complete spec. Database is superfluous since the user specified it (or already knows which database they are working with).
> Simplify CLI output for value edits

- go/nomdl/parser_test.go
- go/types/collection.go
- go/types/list_editor.go
- go/types/map_editor.go
- go/types/map_test.go
- go/types/value.go
We used to ignore empty collections inside a ListEditor which meant that
a list editor could not be used to create lists that contain empty
lists, maps or sets.
Fixes #3868
> Do not ignore empty collections in ListEditor
