attic-labs/noms

- go/datas/remote_database_handlers.go
> Fix some comments in remote_database_handlers.go

- go/types/blob.go
- go/types/blob_test.go
- go/types/rolling_value_hasher.go
- js/package.json
- js/src/blob-test.js
- js/src/blob.js
- js/src/rolling-value-hasher.js
> add Blob.Splice()

- doc/intro.md
- samples/go/nomsfs/basics_test.go
- samples/go/nomsfs/dir_test.go
- samples/go/nomsfs/nomsfs.go
- samples/go/nomsfs/rw_test.go
@aboodman submitting for your final approval
> noms-based fuse implementation

- go/dataset/dataset.go
1) ValueStore now maintains validation cache info across Commit() calls,
so we can remove a workaround in Dataset.Commit()
2) Update comment for setNewHead
3) setNewHead was decomposing a Commit object just so it could pass the pieces to Dataset.Commit()...which put them all back together again. Seemed silly.
> Dataset cleanup

- cmd/noms/diff/diff_test.go
- go/types/struct.go
- go/types/struct_test.go
It inverted the added/removed order.
> Fix struct diff

- samples/js/splore/src/layout.js
- samples/js/splore/src/main.js
- samples/js/splore/src/node.js
- Display the prolly-tree for Blobs
- Fix fallout from sha1-xxx to xxxx
- Make the hashes links to splore rooted at that hash
Fixes #2218
Fixes #1321
> Splore Blobs and more

- cmd/noms/noms.go
- cmd/noms/noms_diff.go
- cmd/noms/noms_ds.go
- cmd/noms/noms_log.go
- cmd/noms/noms_serve.go
- cmd/noms/noms_show.go
- cmd/noms/noms_sync.go
- cmd/noms/noms_version.go
- cmd/util/command.go
- cmd/util/help.go
I needed this so nomdex can reuse the same code.
> Factor our noms Command and Help so they are reusable.

- samples/go/nomsfs/README.md
- samples/go/nomsfs/nomsfs.go
* added a README (merged with Mike's)
* cleaned up Ref<Blob> handling
* automatic unmounting
* signal handling to unmount on exit
> nomsfs: general cleanup

- samples/go/nomsfs/nomsfs.go
... still figuring out how to automate Finder regression testing. And working with the go-fuse maintainer to make this less ugly.
> nomsfs: small fix up for Finder regression

- samples/go/csv/csv-export/exporter.go
- samples/go/csv/csv-export/exporter_test.go
- samples/go/csv/write.go
> implement csv-export writing maps of structs

- samples/go/csv/csv-import/importer.go
- samples/go/csv/read.go
- samples/go/csv/read_test.go
> changing csv-import of map to include pk in struct

- go/types/path.go
- go/types/path_test.go
- js/.eslintrc.js
- js/package.json
- js/src/hash.js
- js/src/noms.js
- js/src/path-test.js
- js/src/path.js
- js/src/struct.js
- js/src/type-cache.js
JS had an incomplete implementation, most notably missing: string
parsing, hash # syntax, and support for hash indices.
> Port path implementation to JS

- samples/go/csv/README.md
Yes I'm that guy. Small typo :)
> I'm that guy fixing a typo

- go/datas/remote_database_handlers.go
really silly simple fix for consistency's sake.
> fix error message

- go/datas/http_batch_store.go
- go/datas/remote_database_handlers.go
> Add better error reporting to HTTPBatchStore::UpdateRoot()

- doc/faq.md
> Update FAQ to address conflict resolution

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
- go/types/list.go
Slices and arrays are marshaled to Noms List. For arrays we also enforce
that the length is the same.
Towards #2376
> Go marshal slices and arrays

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
Go maps are marshaled to Noms Map.
Towards #2376
> Go marshal maps

- go/chunks/chunk.go
- go/constants/version.go
- go/d/try.go
- go/datas/database.go
- go/dataset/dataset.go
- go/spec/dataspec.go
- go/types/type.go
- go/walk/walk.go
> adding godoc synopsis for several top level packages

- doc/cli-tour.md
> Correct typo in cli-tour doc

- samples/go/nomdex/nomdex_find.go
- samples/go/nomdex/nomdex_test.go
- samples/go/nomdex/nomdex_update.go
> Add integration test for nomdex

- samples/go/nomdex/nomdex_find.go
> Describe find command in help output

- samples/go/nomdex/expr.go
- samples/go/nomdex/nomdex_find.go
- samples/go/nomdex/nomdex_test.go
- samples/go/nomdex/parser.go
- samples/go/nomdex/parser_test.go
- samples/go/nomdex/query_range.go
> Add != operator to nomdex query language.

- go/walk/walk_test.go
Remove some unneeded helper functions
> Clean up test code in walk package

- go/perf/suite/suite.go
I hope.
We should stop using Markdown syntax in our public Go docs. godoc
doesn't recognise it (https://godoc.org/github.com/fluhus/godoc-tricks
is a reasonable summary of what *is* supported).
This patch:
- Wraps comments at 100 characters, because godoc doesn't do wrapping.
- Replaces triple-backtick blocks with indented blocks.
- Removes single-backtick lines with entirely.
- Lines things up better.
- An unfortunate side-effect is bullet points are monospaced in
godoc.org, but there isn't a way around this.
> Make the Go doc for go/perf/suite look idiomatic

- tools/build-js-documentation.py
- tools/licensify.py
- tools/roll.py
This script npm installs documentationjs and runs it on noms.js and
puts the output in $WORKSPACE/build
It is intended to be used with Jenkins.
> Build script for building JS SDK Docs

- doc/spelling.md
> Update spelling.md with more syntax and examples

- tools/build-js-documentation.py
Reverts attic-labs/noms#2491
Something else is wrong...
> Revert "Work around python popen bug for js docs"

- go/util/progressreader/reader.go
- samples/go/json-import/json_importer.go
> Add progress reporting to json_importer

- samples/go/noms-merge/main.go
- samples/go/noms-merge/main_test.go
Tests command line validation for noms-merge
Toward #2445
> Add failure tests for noms-merge

- samples/go/noms-merge/main_test.go
This was caused by me changing an error string and failing
to update the test.
> Fix test assertion in noms-merge::TestLose()

- js/perf/viewer/src/main.js
* Increase number of results to 20.
* See newer results at the end of the graph, not start.
* Make point radius show standard deviation to scale.
* Try not to draw datasets over each other.
* Invert light colours to make them darker.
> Improvements to the perf viewer

- js/perf/viewer/src/main.js
> Fix "and and" comment from last patch

- tools/noms/staging.py
Also run pylint on staging.py.
> Check before calling mkdirs on staging directory

- js/perf/viewer/stage.py
- samples/js/splore/stage.py
- tools/noms/staging_test.py
Also fix unit test that was not updated when the functions were
renamed.
> Fix import of noms.staging in stage.py

- js/perf/viewer/stage.py
- samples/js/splore/stage.py
- tools/noms/copy.py
- tools/noms/copy_test.py
- tools/noms/staging_test.py
- tools/noms/symlink.py
- tools/noms/symlink_test.py
Also changes the tabs to spaces. Thanks pylint.
> stage.py needs to import sys before using it

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
- samples/go/csv/csv_reader.go
Adds an error for csv skip records to stop a potential panic, and give the user feedback
Fixes https://github.com/attic-labs/noms/issues/2446
> Adds error for invalid skip records argument and exits csv importer

- js/noms/src/walk.js
The line length exceeded 100 cols
> Fix lint error

- cmd/noms/noms.go
- cmd/noms/noms_commit.go
- cmd/noms/noms_commit_test.go
- go/spec/commit_meta.go
- samples/go/csv/csv-import/importer.go
- samples/go/json-import/json_importer.go
- samples/go/url-fetch/fetch.go
- samples/go/url-fetch/fetch_test.go
- samples/go/xml-import/xml_importer.go
> Add Noms commit command

- js/noms/package.json
This picks up my commits to discover all exported bindings as well as
sorting the docs alphabetically.
> Update to latest documentation.js

- cmd/noms/noms_log.go
Try `noms log http://104.198.2.60::hn`; exiting the pager (in my case `less`) doesn't necessarily exit the `noms` command in a timely fashion (though it depends a bit on when you quit less).
> noms diff should exit after the pager exits

- js/noms/build/make-index-html.js
- js/noms/package.json
Also keep the hash when redirecting
Towards #2532
> Generate js docs in /js/

- tools/build-js-documentation.py
> Add a bare bones landing page to docs.noms.io

- js/noms/package.json
To pick up a bug fix related to sorting
> Update to a newer version of documentation.js

- go/hash/hash.go
- go/types/bool.go
- go/types/number.go
- go/types/string.go
- go/types/value.go
- js/noms/src/compare.js
- js/noms/src/get-hash.js
- js/noms/src/hash.js
> Add jsdoc/godoc for Hash and Value

- go/types/list.go
- go/types/list_iterator.go
- js/noms/src/list.js
> Add jsdoc/godoc for List

- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/set.js
No need to restrict what type of promise the callback returns
> Change type of callback for List/Set/Map forEach

- js/perf/viewer/src/main.js
The 'ds' parameter can now have multiple comma separated datasets, and
every time the page refreshes (which now happens programmatically, not
via location.reload) it shows the next.
> Support multiple perf datasets in the perf UI

- codecov.yml
- tools/noms/staging_test.py
- tools/run_pr_builder.sh
fixing #2509, adding recommended YAML file for better codecov.io integration
> Run python unittests; configure codecov via YAML

- go/merge/three_way.go
- go/merge/three_way_keyval_test.go
- go/merge/three_way_list_test.go
- go/merge/three_way_set_test.go
- go/merge/three_way_test.go
Add some additional tests to cover more failure cases.
> Improve Go merge package code coverage

- tools/run_perf_builder.py
This changes effectively:
> go test ./go/types/perf ./samples/csv/csv-import <etc>
to:
> go test ./go/types/perf <etc>
> go test ./samples/csv/csv-import <etc>
The perf results started going crazy when I started running a second
test package (./go/types/perf), this is one reason why it may have
happened. It's hard to say for sure what go test is doing.
> Update run_perf_builder.py to run 'go test' commands sequentially

- go/merge/three_way_set_test.go
- go/types/encode_human_readable.go
- go/types/encode_human_readable_test.go
- js/noms/src/encode-human-readable-test.js
- js/noms/src/encode-human-readable.js
> Tweak the display of the type of an empty Map

- js/noms/package.json
- js/noms/src/fetch.js
- js/noms/src/put-cache.js
- js/noms/src/struct-test.js
- js/perf/package.json
- samples/js/fb/find-photos/src/main.js
- samples/js/package.json
Motivation: Better libs needed in an upcoming PR.
> Update Flow to 0.32

- js/noms/.gitignore
- js/noms/package.json
- js/noms/src/browser/fetch.js
- js/noms/src/fetch.js
This works around a bunch of issues related to fetch and XMLHttpRequest
in React Native.
> Add work arounds for React Native

- samples/go/csv/csv-import/perf_test.go
Also reuse data already imported as blob by another test.
> Use smaller dataset to testing csv-import/multi-map

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/types/type_cache.go
- go/types/type_cache_test.go
- samples/go/photo-index/main.go
- samples/go/photo-index/main_test.go
Will add indexing by face/geo in subsequent patches.
> Add photo-index: a simple photo indexer. For now only indexes by tag.

- cmd/noms/noms_sync_test.go
- go/d/check_error.go
- go/util/clienttest/client_test_suite.go
- go/util/exit/exit.go
- samples/go/csv/csv-import/importer_test.go
- samples/go/nomdex/nomdex.go
- samples/go/noms-merge/main.go
- samples/go/photo-index/main.go
- samples/go/poke/main.go
- samples/go/poke/main_test.go
- samples/go/url-fetch/fetch.go
Ignore the first commit, it is being reviewed separately.
fyi: @zcstarr, @willhite
> Refactor exit mockery into go/util/exit

- go/datas/dataset.go
- go/datas/dataset_test.go
- go/spec/absolute_path.go
- go/spec/absolute_path_test.go
- samples/go/photo-index/main.go
Ignore the first commit, it is being reviewed separately.
> Factor out datas.ReadAbsolutePaths()

- samples/js/url_fetch/integration_test.go
> Add integration test for sample: url_fetch

- samples/js/aggregate/dummy.go
- samples/js/aggregate/integration_test.go
- samples/js/url_fetch/dummy.go
Also, fix package name in aggregate example.
> Add dummy files to js samples with integration tests

- js/noms/package.json
- js/noms/src/assert-type-test.js
- js/noms/src/commit-test.js
- js/noms/src/commit.js
- js/noms/src/encode-human-readable-test.js
- js/noms/src/encoding-test.js
- js/noms/src/struct-test.js
- js/noms/src/struct.js
- js/noms/src/type-cache-test.js
- js/noms/src/type-cache.js
- js/noms/src/type-test.js
- js/noms/src/type.js
- js/noms/src/value-decoder.js
- js/noms/src/walk-test.js
- js/perf/codec-perf-rig/src/main.js
- samples/js/fb/find-photos/src/main.js
- samples/js/flickr/find-photos/src/main.js
- samples/js/fs/src/main.js
Restructure makeStructType to have sane API, update callers.
> You're the computer, you sort the fields

- samples/go/nomdex/nomdex_find.go
- samples/go/nomdex/nomdex_test.go
- samples/go/nomdex/nomdex_update.go
Also, make help text more complete.
> Add tx-regex, tx-replace, and tx-convert args.

- doc/go-tour.md
- doc/js-tour.md
Whoops, shoulda fixed these with the patches that updated the
APIs.
> Fix JS and Go tour documents to use new Database/Dataset API

- go/config/resolver.go
- go/config/resolver_test.go
- samples/go/photo-index/main.go
PTAL @willhite 
FYI @kalman, @aboodman
> Make config.Resolve methods public and make photo-index .nomsconfig aware

- js/noms/package.json
- js/noms/src/fetch-test.js
- js/noms/src/fetch.js
Detect the protocol and pick the right module as needed.
Fixes #2613
> Allow Node.js to work with https

- js/noms/.flowconfig
- js/noms/package.json
- js/noms/src/bytes.js
- js/noms/src/indexed-sequence.js
- js/noms/src/list.js
- js/noms/src/put-cache.js
This is a work around to make code using React Native work.
> JS: Change FlowIssue style comment

- js/noms/src/specs-test.js
- js/noms/src/specs.js
- samples/js/fb/find-photos/src/main.js
- samples/js/fb/slurp/src/main.js
- samples/js/flickr/find-photos/src/main.js
- samples/js/flickr/slurp/src/main.js
Fixes https://github.com/attic-labs/attic/issues/612
> Track run date and input paths for fb and flickr importers

- samples/js/fb/slurp/src/main.js
Upgrading to v2.8 to support tokens generated from Facebook SDK for iOS.
> Update to Facebook API v2.8

- samples/js/flickr/slurp/src/flickr.js
- samples/js/flickr/slurp/src/main.js
We were using the short lived access token when we should have
exchanged that for a long term access token.
Also refactor the code a bit. Sorry!
> Fix Flickr importer to get an access token

- samples/js/flickr/slurp/src/main.js
This way we get photos that aren't in any album.
Fixes: #2675
> Flickr: import primarily photo-wise rather than album-wise.

- samples/go/photo-index/main.go
Would be nice to also tag with pinned path, but that's more work
> photo-index: tag commit with run date

- samples/js/fb/slurp/src/main.js
We didn't notice this before because none of us had enough fb data to cause it to page.
> fb: fix paging logic

- go/datas/remote_database_handlers.go
- go/datas/remote_database_handlers_test.go
In some cases where the same chunk appears more than once in a given
writeValue request, the handleWriteValue code is able to recognize
this and skip re-decoding and re-hashing it. In that case an empty
result winds up percolating through the code, and I wasn't handling
this correctly. Fixed and added a unit test to catch this.
Fixes #2695
> Fix crash in handleWriteValue

- samples/js/fb/slurp/src/main.js
> fb/slurp: fix eslint error

- CONTRIBUTING.md
Discuss some guidelines for how we do Go error reporting
in Noms code
> Add some info about the  package to CONTRIBUTING.md

- go/spec/absolute_path.go
- go/spec/dataspec.go
Also, add String() method to PathSpec.
> Make AbsolutePath's private fields public.

- samples/js/dropbox/slurp/src/main.js
> dropbox/slurp: add ability to restrict import to a path prefix

- samples/js/dropbox/slurp/src/main.js
> dropbox/slurp: path is optional

- samples/js/picasa/slurp/src/main.js
> picasa/slurp: command-line flags should use dash not underscore

- js/noms/package.json
I forgot to do this when fixing issue #2699
> Bump patch-level NPM module version

- go/merge/three_way.go
Modify the comment in merge/three_way.go to be accurate, add
lengthy discussion of List merge algorithm in three_way_list.go
Fixes #2717
> Go: Add more documentation for List merge.

- js/noms/package.json
- js/noms/src/browser/fetch.js
- js/noms/src/fetch.js
- js/noms/src/http-batch-store.js
- js/noms/src/http-error-test.js
- js/noms/src/http-error.js
And also fix browser/fetch.js to match the node version.
> Fix HTTPError class

- go/types/encoding_test.go
- go/types/value_encoder.go
- js/noms/src/encoding-test.js
- js/noms/src/value-encoder.js
We were hitting iloops for these non finite numbers
> Handle NaN and Infinity in number encoding

- tools/licensify.py
> Followup to licensify.py

- samples/js/fb/find-photos/src/main.js
Moves faces to faces_centered and returns the center point of the face
> Refactors face rectangle to face center point

- cmd/noms/diff/diff.go
- cmd/noms/diff/diff_test.go
- cmd/noms/diff/print_diff.go
- cmd/noms/noms_config.go
- cmd/noms/noms_diff.go
- cmd/noms/noms_log.go
- go/types/path.go
- go/types/path_test.go
The Diff function now returns Difference objects that can be
used in different contexts (e.g. print_diff)
> Extract print functionality from Diff function.

- samples/js/dropbox/find-photos/src/main.js
- samples/js/fb/find-photos/src/main.js
- samples/js/flickr/find-photos/src/main.js
- samples/js/photos/src/photo-grid-item.js
- samples/js/photos/src/photo-grid.js
- samples/js/photos/src/types.js
- samples/js/picasa/find-photos/src/main.js
Ignore first commit, I sent a separate PR for it.
> Fix date grouping logic

- go/types/sequence_chunker.go
- js/noms/src/sequence-chunker.js
Previously we would clone them from the original cursor, to (a) not
modify the original cursor, and (b) have initialization and finalization
not interfere with each other.
However, this isn't necessary and it just creates unnecessary churn. For
example, when we read-ahead, it would be wasteful to re-read the
read-head chunks from initialization.
> Use the same cursor when initializing and finalizing the chunker

- samples/go/face-merge/main.go
- samples/go/face-merge/main_test.go
- samples/go/photo-index/main_test.go
it takes face center points and face rectangles and returns the
set of faces in which the face rectangle contains the face
center point. We return a photo object with a set of faces, that
have the names from the face centerpoints and the rectangles from the
face rectangles.
> Adds face merge functionality to photos

- js/babel-preset-noms/.gitignore
- js/babel-preset-noms/README.md
- js/babel-preset-noms/index.js
- js/babel-preset-noms/package.json
This simplifies dependency handling
> Add a babel-preset-react module

- samples/js/aggregate/package.json
- samples/js/bar-chart/package.json
- samples/js/counter/package.json
- samples/js/dropbox/find-photos/package.json
- samples/js/dropbox/slurp/package.json
- samples/js/fb/find-photos/package.json
- samples/js/fb/slurp/package.json
- samples/js/flickr/find-photos/package.json
- samples/js/flickr/slurp/package.json
- samples/js/fs/package.json
- samples/js/package.json
- samples/js/photos/package.json
- samples/js/picasa/find-photos/package.json
- samples/js/picasa/slurp/package.json
- samples/js/splore/package.json
- samples/js/url_fetch/package.json
This prevents us from doing npm publish on them.
https://docs.npmjs.com/files/package.json#private
> Mark non standalone packages as private

- tools/run_go_bin_builder.py
> Remove old noms-merge command from autobuild binaries list

- go/util/receipts/receipts.go
- go/util/receipts/receipts_test.go
- samples/go/demo-server/main.go
- samples/go/demo-server/web_server.go
- samples/go/demo-server/web_server_test.go
- tools/crypto/receiptkey/main.go
- tools/crypto/receipttool/main.go
Reverts attic-labs/noms#2790
I just realised that removing the demo server requires a whole bunch of deployment changes.
> Revert "Remove demo-server and receipts code"

- samples/go/coffee/main.go
> coffeebot: remove secret url

- samples/go/coffee/main.go
> fix timezone in coffeebot

- samples/js/photos/src/photo-grid.js
Going to do this in the index layer instead so that we can more easily compare different approaches
> Remove temporary time-based dedup from webui

- js/noms/package.json
To pick up links into github for methods
> Use the latest version of documentation.js

- tools/publish-to-npm.py
Jenkins is now running from a different pwd. This changes fixes that and
makes it immune to future changes.
> Change publish-to-npm to work relative to GOPATH not pwd

- go/types/sequence_iterator_test.go
> Fix test break

- go/types/sequence_iterator_test.go
> Better test fix. Need to obtain raw bytes before reading from buffer.

- samples/go/coffee/main.go
this way easier for message to be seen
> coffeebot: don't do anything until 10a each day

- go/marshal/decode.go
- samples/go/photo-index/main.go
Ignore first two commits, they are under review separately.
> Teach photo-index about PhotoGroup

- samples/go/photo-index/main.go
- samples/js/dropbox/find-photos/src/main.js
- samples/js/fb/find-photos/src/main.js
- samples/js/flickr/find-photos/src/main.js
- samples/js/picasa/find-photos/src/main.js
Ignore first three commits as they are being reviewed separately.
> photo-index: index photos by sources too

- samples/js/flickr/find-photos/src/main.js
> Change flickr/find-photoss to store urls under RemoteResource.url

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
The only support that marshal has for Set at the moment is decoding to
slice.
> Improve Set marshaling to add encoding support, and decoding to map

- samples/js/picasa/slurp/src/main.js
> Type erasure for noms :)

- samples/js/splore/src/main.js
Params must include trailing '=' characters for base64 receipts.
> Make splore param parser not strip trailing '=' characters

- samples/go/downloader/downloader.go
- samples/go/downloader/downloader_test.go
Fixes https://github.com/attic-labs/attic/issues/130
> Fix in/out root mixup in downloader.

- samples/js/dropbox/slurp/src/main.js
Toward https://github.com/attic-labs/attic/issues/152
> Change the dropbox client we're using.

- samples/js/photos/src/nav.js
Flow didn't know which type to pick for addEventListener.
> Give Flow a helping hand

- README.md
- codecov.yml
- tools/run_pr_builder.sh
> Revert "Update links to jenkins3.noms.io"

- go/types/type.go
- go/walk/walk_test.go
- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/ref.js
- js/noms/src/set.js
- js/noms/src/struct.js
- js/noms/src/type.js
- js/noms/src/value.js
- js/noms/src/walk-test.js
- js/noms/src/walk.js
> Fix JS walk handling for values of type Type

- js/noms/README.md
> Revert "testing"

- go/types/type.go
- go/walk/walk_test.go
- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/ref.js
- js/noms/src/set.js
- js/noms/src/struct.js
- js/noms/src/type.js
- js/noms/src/value.js
- js/noms/src/walk-test.js
- js/noms/src/walk.js
This reverts commit 2717908d2bf543d71dbe69ba249e4b919fd1a6dd.
> Revert "Fix JS walk handling for values of type Type (#2913)"

- go/types/type.go
- go/walk/walk_test.go
- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/ref.js
- js/noms/src/set.js
- js/noms/src/struct.js
- js/noms/src/type.js
- js/noms/src/value.js
- js/noms/src/walk-test.js
- js/noms/src/walk.js
The promise was resolving too early.
> JS: Fix walk

- go/chunks/chunk_store.go
- go/chunks/dynamo_store.go
- go/chunks/leveldb_store.go
- go/chunks/memory_store.go
- go/datas/http_batch_store.go
- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/store.go
- go/types/batch_store.go
- go/types/validating_batching_sink.go
Add `ChunkSink.Flush()` which signals the ChunkSink that any previously `Put` chunks should be made durable.
Fixes #2876
> ChunkSink.Flush()

- go/nbs/store.go
> Add AWSStoreFactory

- go/nbs/mem_table_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_reader.go
- go/nbs/table_reader.go
- go/nbs/table_set_test.go
- go/nbs/table_test.go
> Make read amplification threshold configurable

- go/nbs/table_set.go
When an nbs store is opened, open each contained table in parallel, rather than serially so as to reduce latency till the store is available to service requests.
> Open NBS tables in parallel

- go/nbs/mem_table_test.go
- go/nbs/mmap_table_reader.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_fake_test.go
- go/nbs/s3_table_reader.go
- go/nbs/table_persister.go
- go/nbs/table_reader.go
- go/nbs/table_set_test.go
- go/nbs/table_test.go
> Factor tableIndex out of tableReader

- go/util/verbose/verbose.go
This would be convenient for me during testing & development.
> Add set methods to verbose.

- samples/js/picasa/slurp/src/main.js
Fixes https://github.com/attic-labs/attic/issues/317
> Fix crash in picasa importer with large albums

- js/noms/package.json
- js/noms/src/type.js
- js/noms/src/value-decoder.js
> Remove unnessary invariants

- go/marshal/encode.go
- go/marshal/encode_test.go
> Add support for `original` in marshal.Marshal

- go/marshal/encode.go
- go/marshal/encode_test.go
> Marshal() should accept `original` field with empty value.

- cmd/noms/noms_show.go
- cmd/noms/noms_show_test.go
> add noms show --raw

- go/spec/spec.go
There's no reason that this shouldn't work, so make it do so
> Enable noms serve to serve nbs-aws stores

- go/types/path.go
- js/noms/src/path-test.js
- js/noms/src/path.js
This brings it much closer to the Go implementation, and eventually
implementing the @at annotation.
> Refactor JS path code and implement @type

- README.md
@aboodman I'm working through the GitHub repos to familiarize myself with the codebase.  I've done a slight tweak to your readme to put some context around what the user is installing.  
This is Mary btw, in case you don't recall my GitHub handle.
> Adding guidance to the README

- go/datas/http_batch_store.go
> fix bug in http_batch_store storing of hints

- go/marshal/encode.go
- go/marshal/encode_test.go
This lets types provide their own Noms value marshaling.
> Add the marshal.Marshaler interface

- go/datas/http_batch_store.go
In the edge case where all source chunks are already present in the
sink AND the sink dataset does not yet exist, the httpBatchStore code
was sending chunks in reverse order.  This patch ensures that,
regardless of how few chunks are sent, any operation that sends chunks
to the server also resets chunk write order.
Fixes #3101
> Fix sync bug when all chunks are already present in the sink

- go/types/value_store.go
> Avoid concurrent access to hashmap

- js/noms/package.json
- js/noms/src/blob.js
- js/noms/src/list.js
- js/noms/src/map.js
- js/noms/src/ref.js
- js/noms/src/set.js
- js/noms/src/struct.js
- js/noms/src/type.js
- js/noms/src/value.js
- js/noms/src/walk-test.js
- js/noms/src/walk.js
> (JS) Implement parallel walk io

- go/marshal/decode.go
When constructing a recursive decoder (e.g, mapDecoder, arrayDecoder, setDecoder),
the new decoder is placed in the cache before its element decoders are created to
avoid a cycle.
If another go routine finds the new decoder in the cache, it can use it before it's
fully initialized.
Use a RWMutex to guard against this. Take the write lock out before adding the decoder
to the cache and release after the element decoders have been initialized.
Use a read lock in the decoder to function go ensure that it blocks until initialization
is complete.
toward: #3071
> Fix race conditions in marshal.typeDecoder

- go/nbs/block_store_test.go
- go/nbs/store.go
- vendor/github.com/jpillora/backoff/.version
- vendor/github.com/jpillora/backoff/README.md
- vendor/github.com/jpillora/backoff/backoff.go
- vendor/github.com/jpillora/backoff/backoff_test.go
> Retry NomsBlockStore.Flush() with exponential backoff

- js/noms/package.json
> bump version because of format version change

- js/noms/src/http-batch-store.js
This allows JS to make authenticated writes to Noms.
> Pass the fetchOptions to writeBatch in HttpBatchStore

- tools/publish-to-npm.py
https://github.com/yarnpkg/yarn/issues/2445
> yarn publish is broken

- go/ngql/README.md
- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
TBR @arv  Sorry, was going to this in the last patch, but forgot. Just name changes. I think this is better than a sea of "value".
> Better naming for graphql fields

- go/datas/remote_database_handlers.go
- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
- samples/js/graphiql/styles.css
- vendor/github.com/graphql-go/graphql/values.go
> GraphQL cleanup

- samples/js/graphiql/src/main.js
> Graphiql JS example: Add simple support for authorization header

- go/ngql/types.go
TBR @arv 
More hackery to get around not translating noms types yet.
> ensure types have a name

- samples/js/graphiql/src/main.js
Steal splore's prompt ui to input db, ds & auth
TBR @arv
> Add config prompt to graphql ui

- go/nbs/root_tracker_test.go
- go/nbs/store.go
> Nbs local store factory

- cmd/noms/noms_commit_test.go
- cmd/noms/noms_log_test.go
- cmd/noms/noms_merge_test.go
- go/config/resolver.go
- go/spec/absolute_path.go
- go/spec/spec.go
- go/spec/spec_test.go
- go/spec/util.go
- go/types/path.go
- samples/go/poke/main_test.go
> Remove Spec.DatasetName and Spec.Spec

- README.md
I think this better reflects where we're at and where we're going.
> Refresh of the Noms homepage

- go/types/list.go
- go/types/map.go
- go/types/map_iterator.go
- go/types/set.go
- go/types/set_iterator.go
- go/types/set_iterator_test.go
These two were missing for Set
> Add Set.IteratorAt and Set.IteratorFrom

- go/nbs/s3_table_reader.go
This is to help create a support case for the S3
connection-reset-by-peer issue we're seeing on prod.
> Add additional logging in s3_table_reader.go

- cmd/noms/noms_ds_test.go
- cmd/noms/noms_sync_test.go
- go/nbs/block_store_test.go
- go/nbs/store.go
- go/spec/spec.go
- go/spec/spec_test.go
- go/util/clienttest/client_test_suite.go
- samples/go/csv/csv-import/importer_test.go
- remove Mkdir from NewLocalStore and NewLocalStoreFactory
- add specific error messages for directory does not exist and path is not a directory
- add tests for missing directory and path not directory
fixes: #3222
> Remove implicit directory creation when creating a local db

- go/datas/database_server.go
- go/datas/remote_database_handlers.go
- samples/js/graphiql/src/main.js
We were using GET and the query was getting too large
> Use POST for GraphQL endpoint

- go/nbs/s3_table_reader.go
The AWS support people need this ID to dig into logs.
Fixes #3206
> Add Request ID to logging when S3 reads fail

- go/ngql/query.go
- go/ngql/query_test.go
- go/ngql/types.go
Go vet was right. Having a function return a non exported type was going
to cause pain.
> NGQL: Export TypeMap

- go/ngql/query_test.go
- go/ngql/types.go
Struct fields are not allowed to be null or missing.
Lists/Sets may not contain null.
> NGQL: Handle null better in input data

- go/nbs/s3_table_reader.go
- go/nbs/s3_table_reader_test.go
We hit the point of diminishing returns with #3255.
Just do retries with an exponential backoff, logging
failures so we can at least go back in logs and see
how often we see this failure in future, and if we
get storms of retries or not.
> Add retries to S3 reading

- samples/js/graphiql/package.json
- samples/js/graphiql/yarn.lock
Hopefully it will fix my startup crash...
> Update graphiql dependency

- go/nomdl/lexer.go
- go/nomdl/parser.go
- go/nomdl/parser_test.go
At this point it only parses the type syntax.
Towards #1466
> Add parser for Noms Types

- go/types/assert_type_test.go
Adding more tests as I'm tracking down issues
> IsSubtype more tests

- go/types/simplify.go
- go/types/simplify_test.go
This replaces all `struct N { ... }` with `struct N {}` in a type
and returns a the types it replaces for future use
> Replace and collect

- go/types/assert_type_test.go
- go/types/type_cache.go
- go/types/value_store.go
- samples/go/hr/test-data/manifest
> Simplify List, Map, Set and Ref types too

- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/file_manifest_test.go
This a) doesn't make semantic sense, and b) doesn't
work with dynamoDB manifests.
> Fix dynamoManifest to properly handle an empty set of tables

- go/marshal/decode.go
- go/marshal/decode_test.go
- go/marshal/encode.go
- go/marshal/encode_test.go
- go/marshal/encode_type.go
- go/marshal/encode_type_test.go
> Go slice to Noms Set mashalling

- go/types/blob.go
We're getting an error here but can't see what it is in the logs.
> NewStreamingBlob: print out err details from reader

- go/datas/database_common.go
- go/types/type.go
Also handle cycles of unnamed structs.
> Compare target hash instead

- doc/cli-tour.md
- doc/go-tour.md
- doc/intro.md
- go/ngql/query_test.go
- go/types/encode_human_readable.go
- go/types/simplify.go
- go/types/type.go
- go/types/type_cache.go
- samples/go/hr/test-data/manifest
- samples/go/nomsfs/README.md
> Zero-tolerance for unnamed struct cycles

- go/types/common_supertype.go
- go/types/common_supertype_test.go
- go/types/type_cache.go
> Remove to unresolved type

- go/types/simplify_test.go
Puts back some tests that were removed in https://github.com/attic-labs/noms/pull/3367.
Note that a few cannot be restored. The ones which contained struct cycles are still omitted. There isn't really a good way to resolve the cycles without simplifying the type. I don't feel good about keeping cycle resolution code around just for those tests.
TBR @arv
> Restore some simplify tests

- go/types/value_store.go
- go/types/value_store_test.go
Before ripping out all the hinting and associated proactive
validation checking, it was impossible to write Values through
the ValueStore API in any way other than bottom-up. That meant
that we could enforce the invariant that a chunk could not
appear in pendingParents unless it was also in pendingPuts.
Now, it's possible to construct legal sequences of calls to
ValueStore that result in this check being violated. Raf and
I don't think that violating this check can actually lead to
an invalid underlying database, as the lazy validation that
replaced the proactive validation should still catch any such
issues.
Fixes #3371
> Loosen checks in ValueStore.bufferChunks

- cmd/noms/noms_log.go
- go/diff/apply_patch.go
- go/diff/print_diff.go
- go/spec/absolute_path.go
- go/types/path.go
- go/types/path_test.go
- samples/go/nomdex/nomdex_update.go
- samples/go/poke/main.go
> Introduce @target annotation for paths

- go/types/value_store.go
This is happening so often it's filling up space on servers. Still need to understand how it's happening.
> Remove warning

- tools/run_pr_builder.sh
> Remove code coverage

- go/chunks/chunk_store.go
- go/datas/database_test.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/pull_test.go
- go/types/value_store.go
Code review changes from #3403 
Forgot to push them up before landing
> Code review changes from #3403

- go/chunks/memory_store.go
- go/chunks/memory_store_test.go
Woops. Attic was using this. Making public again (and added mutex).
TBR @cmasone-attic
> make MemoryStoreFactory public

- go/constants/version.go
- samples/go/hr/test-data/manifest
Should've done this last week when I tweaked the HTTP
protocol to return the current root hash when a POST
to the root/ endpoint fails.
> Rev Noms version

- go/nbs/store.go
> Trigger compaction probabilistically to avoid lots of concurrent attempts

- go/datas/database.go
- go/datas/database_common.go
- go/datas/database_test.go
> databaseCommon -> database

- go/types/list_test.go
- go/types/map.go
- go/types/map_test.go
- go/types/sequence_chunker.go
- go/types/set_test.go
- go/types/struct.go
- go/types/struct_test.go
Add checks for nil in Struct and add tests for the collections too.
Fixes #3439
> Nil is not a valid Value

- go/nbs/store.go
> raise max tables

- go/types/subtype.go
- go/types/subtype_test.go
It bothered me too much to copy this code in Attic, so I added another kinda weird type function to noms.
Still need to add tests, but let me know if you are ok with this approach.
FYI, I refactored the struct section because the existing code was a bit too hard to reason about. I know my version is longer but it's easier to convince myself that it's correct.
> Is subtype disallow extra struct fields

- go/chunks/chunk_store.go
- go/chunks/chunk_store_common_test.go
- go/chunks/memory_store.go
- go/chunks/test_utils.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/pulling.md
- go/datas/remote_database_handlers_test.go
- go/datas/validating_chunk_store.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
- go/nbs/block_store_test.go
- go/nbs/store.go
No one was doing anything more useful than turning around and calling Put on themselves for each chunk.
> Remove PutMany

- go/metrics/histogram.go
- go/metrics/histogram_test.go
- go/nbs/file_table_persister.go
- go/nbs/file_table_persister_test.go
- go/nbs/mem_table.go
- go/nbs/mem_table_test.go
- go/nbs/persisting_chunk_source.go
- go/nbs/persisting_chunk_source_test.go
- go/nbs/root_tracker_test.go
- go/nbs/s3_table_persister.go
- go/nbs/s3_table_persister_test.go
- go/nbs/stats.go
- go/nbs/stats_test.go
- go/nbs/store.go
- go/nbs/table.go
- go/nbs/table_persister.go
- go/nbs/table_persister_test.go
- go/nbs/table_reader.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
- go/nbs/table_test.go
I haven't fixed up the tests. @cmasone-attic, can I get a pre-review before I do.
> Instrument NBS with perf metrics

- go/util/datetime/date_time.go
- go/util/datetime/date_time_test.go
This was landed in the vendor dir by accident here:
https://github.com/attic-labs/attic/pull/1659
> Add datetime.Epoch

- go/types/blob_leaf_sequence.go
- go/types/indexed_sequence_diff.go
- go/types/leaf_sequence.go
- go/types/list_leaf_sequence.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/ordered_sequences_diff.go
- go/types/sequence.go
- go/types/sequence_cursor_test.go
- go/types/set_leaf_sequence.go
> EmptySequenceDiff

- go/nbs/mmap_table_reader.go
Now that we might open/close a file at any time for reading, there's
no value in acutally reffing a file while building a mmapTableReader
in the case where the index is found in the indexCache.
> NBS: Move mmapTableReader I/O into indexCache miss path

- go/nbs/fd_cache.go
- go/nbs/fd_cache_test.go
- go/nbs/file_table_persister_test.go
There was a race in the previous code. On a cache-miss, fdCache
would release its mutex and go os.Open() a file. Once it opened
successfully, fdCache would re-acquire the lock and update the
cache. The problem was that multiple concurrent cache-missers would
open the file and then all stomp on each other as they update the
cache one-by-one.
The problem here is that we don't want to serialize all file opens
by holding the lock while calling os.Open(). This version just checks
the cache again after opening the file and, if there's now a cache
hit it just drops the fd it just opened and refs the one in the cache.
Fixes #3473
> NBS: Deal with concurrent file opens in fdCache

- go/types/map_test.go
TBR @kalman 
This test is a pre-cursor the compressed rolling hash work, which should also reduce the number of "collateral reads" during mutation.
> map mutation test

- go/nbs/block_store_test.go
- go/nbs/conjoiner.go
- go/nbs/conjoiner_test.go
- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/factory_test.go
- go/nbs/file_manifest.go
- go/nbs/file_manifest_test.go
- go/nbs/manifest.go
- go/nbs/root_tracker_test.go
- go/nbs/stats.go
- go/nbs/stats_test.go
- go/nbs/store.go
> Add Read/WriteManifestLatency stats

- go/nbs/stats.go
> add manifest latencies to Stats.String()

- go/nbs/block_store_test.go
- go/nbs/conjoiner.go
- go/nbs/conjoiner_test.go
- go/nbs/dynamo_manifest.go
- go/nbs/dynamo_manifest_test.go
- go/nbs/factory.go
- go/nbs/factory_test.go
- go/nbs/file_manifest.go
- go/nbs/file_manifest_test.go
- go/nbs/manifest.go
- go/nbs/root_tracker_test.go
- go/nbs/store.go
> NBS: add cache-on-write behavior for manifests

- go/nbs/factory.go
> make maxOpenFiles configurable for AWSFactory

- go/metrics/histogram.go
- go/nbs/conjoiner.go
- go/nbs/dynamo_manifest.go
- go/nbs/file_manifest.go
- go/nbs/mmap_table_reader.go
- go/nbs/persisting_chunk_source.go
- go/nbs/s3_table_reader.go
- go/nbs/stats.go
- go/nbs/stats_test.go
- go/nbs/store.go
- go/nbs/table_reader.go
> Add Open/CommitLatency

- go/nbs/store.go
> NBS: Fix race between Rebase() and Commit()

- go/datas/remote_database_handlers.go
- go/nbs/conjoiner.go
- go/nbs/s3_table_reader.go
- go/nbs/store.go
> Remove some uses of Backoff

- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
> Put root in httpChunkStore /getRefs query string

- go/types/sequence_chunker.go
> trivial sequence chunking refactor

- go/datas/database_common.go
- go/datas/database_test.go
- go/diff/apply_patch.go
- go/merge/three_way.go
- go/perf/codec-perf-rig/main.go
- go/types/map.go
- go/types/map_editor.go
- go/types/map_iterator_test.go
- go/types/map_test.go
- go/types/ref_test.go
- go/types/sequence_chunker.go
- go/types/sequence_cursor.go
- samples/go/hr/main.go
- samples/go/nomsfs/nomsfs.go
@kalman, please TBR the re-sequencing part of this patch
@aboodman, please review now MapEditor
> Streaming p tree updates + Map Editor

- go/types/value_store.go
> remove dead code

- go/constants/version.go
- go/types/map.go
- go/types/ordered_sequences.go
- go/types/sequence_chunker.go
- go/types/set.go
- samples/go/hr/test-data/manifest
> Reland advance to fix

- go/nbs/NBS-on-AWS.md
- go/nbs/dynamo_manifest.go
> Basic doc for running NBS on AWS

- go/datas/commit_test.go
- go/datas/database_common.go
- go/datas/database_test.go
- go/diff/apply_patch.go
- go/merge/three_way.go
- go/perf/codec-perf-rig/main.go
- go/types/blob.go
- go/types/bool.go
- go/types/collection.go
- go/types/encoding_test.go
- go/types/list.go
- go/types/map.go
- go/types/map_editor.go
- go/types/map_iterator_test.go
- go/types/map_test.go
- go/types/number.go
- go/types/ref.go
- go/types/ref_test.go
- go/types/set.go
- go/types/set_editor.go
- go/types/set_test.go
- go/types/string.go
- go/types/struct.go
- go/types/type.go
- go/types/value.go
- go/types/walk_test.go
- samples/go/hr/main.go
- samples/go/nomsfs/nomsfs.go
Tests for nested editors coming. Please review now.
@aboodman 
cc @kalman 
Fixes #3561
> Introduce SetEditor, Nestable Editors

- go/datas/http_chunk_store.go
> Fix httpChunkStore race between Put/Commit and Close

- go/nbs/factory.go
- go/nbs/manifest.go
- go/nbs/manifest_cache.go
- go/nbs/manifest_cache_test.go
This lands https://github.com/attic-labs/noms/pull/3577
> debounce concurrent calls to Rebase()

- go/types/blob.go
- go/types/blob_editor.go
- go/types/blob_editor_test.go
- go/types/blob_test.go
- go/types/list_editor.go
- go/types/list_editor_test.go
- samples/go/nomsfs/nomsfs.go
Towards #3562
Adds `BlobEditor` (which implements `ReadWriteSeeker`) and removes mutative method from Blob.
> BlobEditor

- go/nbs/mem_table.go
- go/nbs/stats.go
> record logical (uncompressed) bytes per persist in metrics

- go/nbs/mem_table.go
> use real uncompressed count

- go/nbs/mem_table.go
- go/nbs/stats.go
- go/nbs/table_writer.go
> further nbs stats cleanup

- go/types/map.go
- go/types/map_test.go
- go/types/set.go
- go/types/set_test.go
> Ensure NewStreamingMap and NewStreamingSet panic when input is not ordered

- cmd/noms/noms.go
- cmd/noms/noms_blob.go
- cmd/noms/splore/noms_splore.go
- cmd/noms/splore/noms_splore_test.go
- cmd/util/kingpin_command.go
Make it use kingpin, and clean up tests.
> Improve command line parsing of noms splore

- go/ngql/query_test.go
- go/ngql/types.go
This is in preparation for passing in a ValueReader to collection
constructors.
> Pipe through ValueReader in ngql

- cmd/noms/splore/noms_splore.go
- cmd/noms/splore/noms_splore_test.go
Display names are relatively similar to `noms show`.
I've also changed the display names for struct values to be more similar
to `noms show`.
> Implement type sploring

- go/perf/suite/suite_test.go
> Skip more perf suite tests

- go/metrics/histogram.go
- go/metrics/histogram_test.go
> allow for samples > 1 << 63

- go/ipfs/cs.go
- samples/go/ipfs-chat/importer.go
- samples/go/ipfs-chat/main.go
> Add rate limit to ipfs chunkstore, increase thread limit

- cmd/noms/noms.go
- cmd/noms/noms_diff.go
- cmd/noms/noms_diff_test.go
Fixes #3526 
My first PR here, so go easy :) 
I have signed the contributor agreement.
> Rename --summarize flag to --stat

- doc/go-tour.md
Some of the Go examples in the tour were broken so I've updated them to working versions. The one with the largest change is appending to a list where I've used a list editor which I think is the replacement for the Append method which has been removed from lists.
> Bring noms-tour up to date with recent changes

- samples/go/url-fetch/fetch.go
- samples/go/url-fetch/fetch_test.go
> Use ETag/If-None-Match in url-fetch

- cmd/noms/commit_iterator.go
- cmd/noms/splore/noms_splore_test.go
- go/hash/hash.go
- go/ipfs/cs.go
- go/metrics/histogram.go
- go/nbs/file_manifest.go
- go/types/blob.go
- go/types/encode_human_readable.go
- go/types/graph_builder.go
- go/types/path.go
- go/types/simplify_test.go
- go/types/struct.go
- go/types/subtype_test.go
- go/util/exit/exit.go
- go/util/functions/all.go
- go/util/random/id.go
- go/util/sizecache/size_cache.go
Just some trivial documentation cleanup, mostly detected with golint. A couple of gofmt'd files.
> Fix godoc strings for several functions

- go/datas/pull.go
This patch implements a new strategy for Pull() that pulls the chunks
from a given level of the graph over in the order they'll be
encountered by clients reading the graph.
Fixes #2968
> Stop noms sync from destroying locality

- samples/go/csv/csv-invert/main.go
Tweaking the main loop that processes list entries to avoid some
map assignments, lookups, and allocations saves 15% or so, resulting
in an overall savings of about 1m on the 6m runtime of our test
workload (as run on my laptop).
Towards #3690
> csv-invert: Perf improvments!

- go/types/type.go
- go/types/type_desc.go
> Clean up Type WalkValues

- tools/run_go_bin_builder.py
> Don't build blob-get

- go/hash/hash.go
- go/nbs/frag/main.go
- go/types/indexed_sequences.go
- go/types/meta_sequence.go
- go/types/value_stats.go
- go/types/value_store.go
- go/types/value_store_test.go
- go/types/walk.go
The order of the values is the same as the order of the hashes.
This way we can easily map the hash to the value.
Motivation #3710
> Change ReadMany to do HashSlice -> ValueSlice

- go/types/simplify.go
growslice was showing up in a csv-import
> Make sure we allocate the right size

- samples/go/csv/csv-import/importer.go
- samples/go/csv/csv-import/importer_test.go
- samples/go/csv/read.go
- samples/go/csv/read_test.go
- samples/go/csv/write_test.go
Added --invert argument to indicate column major order
Added --append argument to append imported data to current head of dataset
Added --limit-records to import data for limited number of rows
> Add ability to import csv in column major order

- go/types/blob_leaf_sequence.go
- go/types/leaf_sequence.go
- go/types/meta_sequence.go
- go/types/ref.go
- go/types/struct.go
- go/types/value.go
Cleanup from https://github.com/attic-labs/noms/commit/1c9d87e6fd7ffb52fe735a3b1f839176acdcd710
> move WalkRefs to valueImpl

- cmd/noms/noms.go
- cmd/noms/noms_stats.go
- go/chunks/chunk_store.go
- go/chunks/memory_store.go
- go/constants/http.go
- go/datas/http_chunk_store.go
- go/datas/http_chunk_store_test.go
- go/datas/remote_database_handlers.go
- go/ipfs/cs.go
- go/nbs/benchmarks/file_block_store.go
- go/nbs/benchmarks/null_block_store.go
- go/nbs/block_store_test.go
- go/nbs/store.go
- go/nbs/table_set.go
- go/nbs/table_set_test.go
Prints a summary of stats for the given DB
> Add noms stats command

- go/nbs/aws_table_persister.go
> NBS: Add rate limiting to Conjoin code pathways

- go/types/blob_leaf_sequence.go
- go/types/leaf_sequence.go
- go/types/list.go
- go/types/map_leaf_sequence.go
- go/types/meta_sequence.go
- go/types/sequence.go
- go/types/value_decoder.go
Also, clean up value decoder to reduce code duplication.
Fixes #3759
> Compute length of collection when creating it

- cmd/noms/noms.go
- cmd/noms/noms_blob.go
- cmd/noms/noms_struct.go
- cmd/noms/noms_struct_new.go
- go/spec/absolute_path.go
- go/spec/absolute_path_test.go
Field values can be literal bool/number/string, or absolute paths in the same database.
> Introduce `noms struct new`

- Dockerfile
See: https://github.com/attic-labs/noms/issues/3789#issuecomment-410893602
> Add a few environment variables per suggestion

- cmd/noms/noms_blob.go
- cmd/noms/noms_blob_put.go
Now that we have cli manipulation tools, no need.
> `noms blob put` no longer auto-commits

- go/nbs/store.go
> Quick fix for hitting open file limit on osx

- go/types/sequence_concat.go
> Remove incorrect assertion

- go/types/map_editor.go
- go/types/map_test.go
> fix mapeditor bug

- cmd/noms/noms_serve.go
- go/datas/database_server.go
- go/perf/suite/suite.go
Hi folks, this is a small change that allows the user to configure the listening address for the db server, besides the port.
> configurable listen address for db server
